import { createGuides, type GuideBlueprint } from "../blueprintFactory";
import type { MathBite, TestPlan } from "../types";

const math = (title: string, formula: string, variables: string[], substitution: string, result: string, interpretation: string, assumptions: string): MathBite => ({ title, formula, variables, substitution, result, interpretation, assumptions });
const test = (firstTest: string, success: string, measure: string, variable: string, controls: string, trials: string[]): TestPlan => ({ firstTest, success, measure, variable, controls, trials });
function householdMaterials(...special: [string, string, string, string, string, ...string[]]): GuideBlueprint["materials"] { return special; }

const blueprints = [
  {
    number: 66,
    title: "Rubber Band Car",
    slug: "rubber-band-car",
    difficulty: "Beginner",
    ageRange: "10-16",
    estimatedTime: "45-70 min",
    timeMinutes: 70,
    maxCost: 8,
    description: "Store energy in a twisted rubber band, release it through the drive axle, and tune a lightweight car for distance.",
    hook: "Wind the rear axle and the rubber band stores elastic energy. Wheel size, axle friction, alignment, and traction decide how much of that energy becomes forward travel.",
    outcome: "The car releases safely, rolls at least 3 metres on a smooth floor, and stays within 50 cm of a straight test lane.",
    concepts: ["Elastic potential energy", "Wheel circumference", "Friction"],
    featured: true,
    input: "twisting stored in a rubber band",
    output: "rear-axle rotation and forward travel",
    motion: "elastic twist-to-rotary vehicle motion",
    losses: ["axle friction", "wheel slip", "chassis rubbing", "air drag"],
    principleName: "Elastic energy propulsion",
    principle: "Twisting stretches parts of the rubber band and stores elastic potential energy. On release, the band applies torque to the drive axle until it unwinds.",
    observe: "Mark the drive wheel and count rotations while comparing measured travel with ideal wheel rollout.",
    materials: householdMaterials("1|10 × 25 cm corrugated-cardboard chassis|Hold axles and rubber band", "2|drinking straws about 12 cm|Create axle bearings", "2|straight skewers or pencils|Serve as axles", "4|equal bottle caps or cardboard wheels|Contact the floor", "1|long rubber band in good condition|Store energy", "1|paper clip hook|Anchor the band at the front"),
    extraTools: ["Adult-made wheel-center holes"],
    alternative: "Use cardboard disk wheels and rolled-paper axles when bottle caps or skewers are unavailable.",
    hazard: "Wear eye protection, inspect the rubber band before each run, and never overwind or aim the car at people.",
    accessNote: "Use a winding key on the drive axle and large high-contrast lane marks.",
    steps: ["Square the chassis|Cut a flat rectangle and draw two axle lines perpendicular to its centerline.|Reinforce any curled edge with tape.", "Attach straw bearings|Tape one straw along each axle line and measure equal overhang.|Sight through both straws to confirm they are parallel.", "Prepare the axles|Slide straight skewers through the straws and confirm free rotation.|Trim sharp points with adult help and cover ends.", "Build and center wheels|Pierce wheel centers accurately and secure one at each axle end.|Spin each axle and correct visible wobble.", "Anchor the rubber band|Attach one end at the chassis front and loop the other around the rear axle center.|Keep the band clear of the floor and straws.", "Add a winding key|Tape a small crosspiece to the drive axle for controlled winding.|Mark a safe maximum turn count after low-turn trials.", "Run the first release|Wind ten turns, set the car on a clear lane, and release without pushing.|Measure distance and sideways drift.", "Tune one variable|Repeat with 10, 20, and 30 safe turns or two wheel sizes.|Keep surface, lane, chassis, and release method fixed."
    ],
    math: math("Predict wheel rollout", "distance = wheel turns × π × diameter", ["Wheel diameter = 0.06 m", "Wheel turns = 15"], "distance = 15 × 3.14 × 0.06 = 2.83 m", "Fifteen ideal rotations travel about 2.8 metres.", "Larger wheels travel farther per turn but need more axle torque.", "Slip and band torque variation reduce real distance."),
    test: test("Push the unwound car gently to confirm all wheels roll before winding.", "The car travels at least 3 metres and remains within 50 cm of the lane center.", "Distance, drift, drive-wheel turns, and unwind time.", "the number of safe band turns", "car, wheels, floor, lane, release, and band", ["10 turns", "20 turns", "30 turns if the band remains relaxed enough"]),
    failures: ["The car curves sharply|Axles are not parallel or wheel diameters differ|Roll it unwound down the lane|Realign straws and match wheels", "The drive wheels spin in place|Traction is low or torque releases too quickly|Watch the first second|Add rubber tread or use fewer turns", "The band tangles|It is off-center or catches the chassis|Wind while holding the car upside down|Add a centered guide and clearance", "The car barely moves|Axle friction is high|Test each axle without the band|Straighten bearings and add side gaps"],
    tuning: "Straight alignment creates more distance than extra winding. More turns increase stored energy but can cause wheel slip or band failure; larger wheels trade drive force for rollout.",
    extensions: ["Easier|Ten-turn baseline|Build for a reliable one-metre run.", "Performance|Wheel-size study|Compare two diameters with equal winding.", "Advanced|Energy estimate|Measure band force over stretch and compare with car motion."],
    related: ["balloon-powered-car", "rolling-can-racer", "gear-ratio-race"],
    builderMoment: "The car was designed for distance and chose a very confident left turn."
  },
  {
    number: 67,
    title: "Balloon-Powered Car",
    slug: "balloon-powered-car",
    difficulty: "Beginner",
    ageRange: "10-16",
    estimatedTime: "40-65 min",
    timeMinutes: 65,
    maxCost: 8,
    description: "Use air escaping from a balloon through a straw nozzle to propel a lightweight car and compare nozzle size.",
    hook: "The balloon pushes air backward, and the car receives a forward reaction force. A smaller nozzle usually releases air longer, while a larger nozzle can produce a stronger short burst.",
    outcome: "The car travels at least 2 metres on a clear floor, releases without hand push, and completes three consistent trials within 25 percent distance spread.",
    concepts: ["Newton's third law", "Thrust", "Airflow"],
    input: "pressurized air escaping backward",
    output: "forward vehicle acceleration",
    motion: "air jet-to-linear vehicle motion",
    losses: ["axle friction", "air leaks", "wheel slip", "aerodynamic drag"],
    principleName: "Action-reaction thrust",
    principle: "The car exerts a backward force on the escaping air, and the air exerts an equal forward force on the car. Thrust lasts only while pressure and airflow remain.",
    observe: "Point the nozzle straight backward and compare motion with the nozzle angled slightly sideways.",
    materials: householdMaterials("1|10 × 22 cm lightweight cardboard chassis|Support wheels and balloon", "2|drinking-straw bearings|Guide axles", "2|straight skewers with covered ends|Serve as axles", "4|equal lightweight wheels|Reduce rolling resistance", "1|new balloon|Store pressurized air", "1|straight drinking-straw nozzle and tape|Direct airflow"),
    extraTools: ["Clothespin for sealing the nozzle"],
    alternative: "Use a reusable party balloon only if it passes a leak test; avoid latex when allergies are present.",
    hazard: "Balloon pieces are choking hazards; inspect for latex allergies, wear eye protection, and discard damaged balloons immediately.",
    accessNote: "Use a clothespin release and a wide inflation straw so the builder does not need to pinch the nozzle.",
    steps: ["Build a straight chassis|Mark two perpendicular axle lines on a light flat base.|Keep the rear area clear for the balloon.", "Install axle bearings|Tape equal straw lengths exactly along the lines.|Test parallel alignment with a ruler.", "Add axles and wheels|Center all wheels and leave side clearance from the chassis.|Roll unwound to check straightness.", "Make an airtight nozzle|Insert the straw a few centimetres into the balloon neck and tape the seal.|Inflate slightly and listen for leaks.", "Mount the balloon|Tape the nozzle along the chassis centerline pointing backward.|Support the balloon without squeezing its expansion.", "Add a release clip|Inflate through the straw, pinch with a clothespin, and place at the start line.|Keep faces away during inflation.", "Run three baseline trials|Remove the clip without pushing and measure distance.|Record inflation size and travel time.", "Compare nozzle openings|Use removable paper sleeves to narrow the same nozzle.|Keep balloon circumference and floor constant."
    ],
    math: math("Compare trial consistency", "range percentage = (maximum - minimum) / average × 100%", ["Distances = 2.0, 2.2, 2.1 m", "Average = 2.1 m"], "range = 0.2/2.1 × 100% = 9.5%", "The three runs vary by about 9.5 percent.", "Lower variation suggests a repeatable release.", "Balloon pressure is difficult to reproduce exactly."),
    test: test("Roll the car by hand before installing the inflated balloon.", "Three releases exceed 2 metres and show less than 25 percent distance spread.", "Travel distance, time, and sideways drift.", "the nozzle opening", "balloon circumference, car, surface, lane, release, and trial count", ["full straw", "medium sleeve", "small sleeve"]),
    failures: ["Air leaks before release|Balloon-straw seal is loose|Inflate and hold underwater only if latex safe and adult supervised|Retape the dry joint", "The car spins|Nozzle points sideways or axles misalign|Test rolling without air|Center nozzle and square bearings", "The balloon rubs wheels|Mount is low or inflation too large|Inflate while lifting the car|Raise support or reduce volume", "The car barely moves|Nozzle is blocked or rolling friction high|Feel airflow and spin axles separately|Clear nozzle and realign wheels"],
    tuning: "A straight nozzle and low rolling friction make thrust useful. Narrowing the nozzle extends the push but can lower peak force; compare distance and time together.",
    extensions: ["Easier|One nozzle size|Optimize only straight travel.", "Performance|Mass study|Add small equal masses and compare acceleration.", "Creative|Target stop|Tune inflation so the car stops inside a marked zone."],
    related: ["rubber-band-car", "balloon-hovercraft", "wind-powered-sail-car"],
    builderMoment: "The nozzle pointed backward. The car still found a diagonal interpretation."
  },
  {
    number: 68,
    title: "Paper Bridge Challenge",
    slug: "paper-bridge-challenge",
    difficulty: "Beginner",
    ageRange: "10-16",
    estimatedTime: "35-55 min",
    timeMinutes: 55,
    maxCost: 3,
    description: "Fold one sheet of paper into a bridge that spans 20 cm and compare how cross-section shape changes load capacity.",
    hook: "Flat paper bends easily, but folds move material away from the center and create a deeper beam. The same sheet can become dramatically stronger without adding mass.",
    outcome: "The bridge spans 20 cm, supports at least 20 coins at midspan for ten seconds, and shows a documented failure location.",
    concepts: ["Bending", "Second moment of area", "Load paths"],
    input: "downward coin load at midspan",
    output: "internal bending resistance across the span",
    motion: "static load-to-beam deflection",
    losses: ["paper creasing", "support slip", "local buckling", "asymmetric loading"],
    principleName: "Beam depth and bending stiffness",
    principle: "Folding paper into a deeper cross-section places material farther from the neutral axis, increasing resistance to bending even though the paper mass stays the same.",
    observe: "Watch whether failure begins by overall sag, top-edge buckling, or a crease near the support.",
    materials: householdMaterials("3|sheets of identical printer paper|Create three bridge shapes", "2|books or boxes spaced 20 cm apart|Form supports", "40|equal coins or washers|Apply measured load", "1|small paper loading cup|Keep load centered", "1|ruler|Measure span and deflection"),
    alternative: "Use identical newspaper rectangles and labeled washers when printer paper or coins are unavailable.",
    hazard: "Keep supports low, catch falling coins in a tray, and wash hands after handling shared currency.",
    accessNote: "Pre-mark fold lines and assign folding, loading, counting, and observing roles.",
    steps: ["Set the test span|Place two equal supports exactly 20 cm apart on a nonslip surface.|Mark the centerline between them.", "Test a flat control|Lay one unfolded sheet across the gap and place the empty cup at center.|Add coins one at a time until failure.", "Fold an accordion beam|Make equal 2 cm alternating folds along the second sheet.|Keep every crease parallel to the span.", "Test the accordion|Center it on the same supports with the same cup.|Load at the same rate and record failure.", "Fold a channel beam|Turn up two 3 cm side walls on the third sheet.|Keep the flat web and both flanges straight.", "Test the channel|Repeat the exact loading process and note deflection at ten coins.|Stop after failure or forty coins.", "Inspect failure modes|Circle the first buckle, crease, or tear on each sheet.|Photograph or sketch the side view.", "Compare designs|Calculate load-to-paper ratio and explain why shape changed strength.|Keep all sheets for evidence."
    ],
    math: math("Compare load improvement", "improvement = folded capacity / flat capacity", ["Flat bridge = 4 coins", "Folded bridge = 24 coins"], "improvement = 24/4 = 6", "The folded section carries six times the flat-sheet load.", "The paper amount did not change; geometry changed stiffness and stability.", "Coin placement and crease quality affect capacity."),
    test: test("Load the flat sheet first as a control.", "At least one folded design spans 20 cm and supports 20 coins for ten seconds.", "Failure load, deflection at ten coins, and failure location.", "the cross-section shape", "paper size, span, supports, coins, cup, and loading rate", ["flat sheet", "accordion", "channel"]),
    failures: ["The bridge slides off|Support contact is small or surface slick|Push sideways before loading|Add nonslip paper under supports", "One side collapses first|Folds or load are asymmetric|Measure edges and cup position|Refold evenly and center the cup", "The loading cup punches through|Contact area is too small|Inspect a local dent under the cup|Add one identical load-spreader card", "Results vary widely|Coins are added at different speeds or positions|Review the test video or record|Use one loader and fixed count rhythm"],
    tuning: "Increase section depth without creating unsupported thin walls that buckle. Sharp consistent folds help, but crushing a crease during setup permanently weakens the beam.",
    extensions: ["Easier|Two-shape comparison|Test only flat and accordion sections.", "Performance|Mass efficiency|Divide supported mass by bridge mass.", "Advanced|Longer span|Predict capacity when span grows to 30 cm."],
    related: ["strongest-index-card-beam", "bridge-under-budget", "straw-truss-bridge"],
    builderMoment: "The paper did not become stronger. It became geometrically persuasive."
  },
  {
    number: 69,
    title: "Paper Tower Challenge",
    slug: "paper-tower-challenge",
    difficulty: "Beginner",
    ageRange: "10-16",
    estimatedTime: "35-60 min",
    timeMinutes: 60,
    maxCost: 3,
    description: "Build the tallest freestanding tower from limited paper and tape, then evaluate buckling, base width, and bracing.",
    hook: "Tall structures fail long before the paper tears. Slender columns buckle, wide bases consume material, and tiny braces can prevent a whole frame from leaning.",
    outcome: "The tower stands unsupported for 30 seconds, reaches at least 60 cm, and survives a gentle tabletop tap without collapsing.",
    concepts: ["Buckling", "Triangulation", "Center of mass"],
    input: "gravity and small lateral disturbances",
    output: "stable vertical structure",
    motion: "static compression with possible sway",
    losses: ["column buckling", "joint peeling", "base rocking", "top-heavy mass"],
    principleName: "Slender-column stability",
    principle: "Long narrow columns can bow sideways under compression. Rolling paper into tubes, shortening unsupported lengths, and triangulating frames raise stability without much added material.",
    observe: "Watch the first part that curves or leans during a gentle tap instead of only noting the final collapse.",
    materials: householdMaterials("10|sheets of identical printer paper|Provide the full material budget", "50 cm|masking tape measured before building|Join members", "1|flat test board|Define the footprint", "1|ruler or tape measure|Measure tower height and base", "1|timer|Verify freestanding duration"),
    alternative: "Use ten equal newspaper rectangles and the same tape length for every team.",
    hazard: "Build from floor or table height and do not stand on furniture to reach the tower top.",
    accessNote: "Offer pre-rolled tubes and roles for layout, joint making, bracing, measuring, and testing.",
    steps: ["Set the material budget|Count ten sheets and cut exactly 50 cm of tape before building.|Return unused pieces to the budget pile.", "Choose a base geometry|Sketch a triangle or square footprint no wider than 30 cm.|Mark corner positions on the test board.", "Make consistent columns|Roll paper diagonally into tight tubes and tape only the final seam.|Produce at least three equal lower columns.", "Build the first level|Join columns with horizontal members and keep the frame vertical.|Measure diagonals before adding height.", "Add triangulation|Brace at least two faces with diagonal strips or tubes.|Avoid heavy tape lumps high on the tower.", "Taper the upper levels|Use shorter, lighter members as height increases.|Keep the center of mass above the base polygon.", "Run a standing test|Release all hands and time 30 seconds.|Record visible sway and the first weak joint.", "Run a gentle tap test|Tap the board, not the tower, once from each side.|Reinforce one failure point within the remaining budget."
    ],
    math: math("Calculate slenderness", "slenderness ratio = unsupported length / member width", ["Unsupported length = 30 cm", "Tube diameter = 2 cm"], "ratio = 30/2 = 15", "The column is fifteen times as long as it is wide.", "Lower ratios generally resist buckling better.", "Paper tube shape, wall thickness, and joints also matter."),
    test: test("Stand the first completed level for ten seconds before adding height.", "The finished tower exceeds 60 cm and stands for 30 seconds after release.", "Height, base width, sway, and failure location.", "the diagonal-brace pattern", "paper, tape budget, footprint, test board, timer, and tap", ["no diagonal control", "one braced face", "two braced faces"]),
    failures: ["A column bows|Unsupported length is large|Sight along the column under self-weight|Add a mid-height brace", "The base rocks|Feet are uneven or footprint narrow|Press each base corner|Trim or widen within budget", "Joints peel|Tape load direction pulls the edge|Inspect the first lifting tab|Wrap joints or change load path", "The top leans|Upper mass is off-center|Drop a visual plumb line|Move light members over the base center"],
    tuning: "Spend material where buckling begins, not evenly everywhere. A broad stiff base improves stability but leaves less paper for height; tapering balances the tradeoff.",
    extensions: ["Easier|Forty-centimetre target|Focus on a stable three-level frame.", "Performance|Efficiency score|Divide height by paper mass used.", "Advanced|Wind test|Use a fan on low from a fixed distance and measure sway."],
    related: ["load-bearing-tower", "longest-paper-cantilever", "center-of-mass-balancing-sculpture"],
    builderMoment: "The tower reached sixty centimetres and discovered lateral loading."
  },
  {
    number: 70,
    title: "Straw Truss Bridge",
    slug: "straw-truss-bridge",
    difficulty: "Intermediate",
    ageRange: "11-17",
    estimatedTime: "75-110 min",
    timeMinutes: 110,
    maxCost: 8,
    description: "Build two triangulated side trusses from straws and connect them into a bridge that carries a centered test load.",
    hook: "Triangles keep the frame from changing shape, but only when joints and compression members stay straight. The bridge turns a pile of flexible straws into a load path.",
    outcome: "The bridge spans 40 cm, supports at least 500 grams for ten seconds, and shows a documented tension or compression failure mode.",
    concepts: ["Trusses", "Tension and compression", "Triangulation"],
    input: "downward midspan test load",
    output: "axial forces carried to two supports",
    motion: "static loading with structural deflection",
    losses: ["joint slip", "straw buckling", "deck twist", "asymmetric load"],
    principleName: "Triangulated load paths",
    principle: "Ideal pin-jointed trusses carry loads mainly as tension or compression along members. Triangles preserve shape, while slender compression straws need bracing against buckling.",
    observe: "Mark likely compression members and watch which one bows before the bridge loses capacity.",
    materials: householdMaterials("40|straight drinking straws|Form truss members", "1 roll|masking tape|Create compact joints", "1|10 × 45 cm light cardboard deck|Connect both trusses", "2|books spaced 40 cm apart|Provide supports", "1|loading cup and masses up to 1 kg|Apply controlled load", "1|catch tray|Contain falling weights"),
    alternative: "Roll paper tubes of equal length when plastic straws are unavailable.",
    hazard: "Keep the bridge low over a tray, add masses gradually, and keep feet and hands away from falling loads.",
    accessNote: "Use a full-size truss layout and color-code tension and compression predictions.",
    steps: ["Draw a full-size side layout|Mark a 40 cm span, 10 cm height, and equal triangular panels.|Use the drawing for both trusses.", "Cut matched members|Trim straws to fit between joint centers and group equal lengths.|Avoid crushing the ends.", "Build the first truss|Tape members directly over the layout with compact joints.|Keep top and bottom chords straight.", "Duplicate the second truss|Build a mirror copy over the same guide.|Overlay finished sides to compare geometry.", "Connect the deck|Stand trusses parallel and tape the deck between their lower chords.|Keep spacing constant along the span.", "Add cross bracing|Join top chords with X or diagonal braces in at least three locations.|Check the bridge resists twisting.", "Run a preload test|Center an empty cup, then add 100 grams.|Measure midspan deflection and inspect joints.", "Load to target|Add 100-gram steps up to 500 grams or first failure.|Stop after ten seconds at each level and record the first deformation."
    ],
    math: math("Find load per support", "support reaction = centered load / 2", ["Total centered load = 500 g", "Two symmetric supports"], "reaction = 500/2 = 250 g equivalent at each support", "Each support carries about half the centered load.", "Internal member forces can be much larger than this simple reaction.", "The relation assumes symmetric geometry and centered loading."),
    test: test("Place an empty loading cup at exact midspan before adding masses.", "The bridge spans 40 cm and supports 500 grams for ten seconds.", "Maximum load, midspan deflection, and first failure location.", "the side-truss diagonal pattern", "span, straw count, tape, deck, support, and loading rate", ["vertical panels", "alternating diagonals", "X-braced panels"]),
    failures: ["The top chord bows|Compression length is too long|Watch the top edge during loading|Add panel-point bracing", "One truss carries more|Deck or load is off-center|Measure cup distance to both sides|Recenter and stiffen cross connections", "Joints peel|Tape area or wrap direction is weak|Inspect the first opening joint|Use compact wraps around both members", "The bridge twists|Cross bracing is missing|Push one top chord sideways when unloaded|Add top and end bracing"],
    tuning: "Shorten unbraced compression lengths and keep joints centered on the member axes. Extra tape adds joint strength and dead weight, so use compact wraps rather than large flat patches.",
    extensions: ["Easier|Twenty-centimetre truss|Build one short truss and test by hand.", "Performance|Strength-to-mass|Divide supported mass by bridge mass.", "Advanced|Moving load|Roll a fixed mass across and map deflection."],
    related: ["paper-bridge-challenge", "bridge-under-budget", "strongest-index-card-beam"],
    builderMoment: "The truss carried the load until one straw remembered it was mostly air."
  },
  {
    number: 71,
    title: "Bottle-Cap Pulley Crane",
    slug: "bottle-cap-pulley-crane",
    difficulty: "Beginner",
    ageRange: "10-16",
    estimatedTime: "55-85 min",
    timeMinutes: 85,
    maxCost: 6,
    description: "Build a tabletop crane with a bottle-cap pulley, rotating boom, hand winch, and lightweight hook.",
    hook: "A pulley redirects the lifting line, the boom carries compression, and the rear tie carries tension. The crane works only when the base keeps the combined center of mass inside its footprint.",
    outcome: "The crane lifts 50 grams through 20 cm, rotates the load through a quarter turn, and stays upright throughout the test.",
    concepts: ["Pulleys", "Moments", "Structural bracing"],
    input: "hand rotation of a winding drum",
    output: "vertical lift at a boom tip",
    motion: "rotary winch-to-linear lift",
    losses: ["pulley friction", "string rubbing", "boom flex", "base tipping"],
    principleName: "Crane moment balance",
    principle: "The suspended load creates a tipping moment equal to force times horizontal reach. A broad base, rear counterweight, and tension tie resist that moment while the winch controls height.",
    observe: "Move the same load closer to and farther from the mast and compare base lifting tendency.",
    materials: householdMaterials("1|20 × 25 cm cardboard base|Support the crane", "1|30 cm rolled-paper mast and 25 cm boom|Carry the lifting path", "1|bottle cap with centered hole|Act as tip pulley", "1|pencil winch drum and 80 cm string|Lift the load", "1|paper-clip hook and masses up to 50 g|Provide test load", "1|small rear counterweight under 100 g|Improve stability"),
    alternative: "Use a thread spool or smooth binder ring instead of a bottle-cap pulley.",
    hazard: "Lift only small masses over a tray and keep hands away from the suspended-load path.",
    accessNote: "Use a large winch handle and a hook with a broad easy-grip tab.",
    steps: ["Reinforce the base|Laminate the mast area and add folded feet around the footprint.|Mark the rotation center and front edge.", "Build the mast|Roll a tight tube and brace it vertically with three triangular gussets.|Check with a square from two directions.", "Build and tie the boom|Attach the boom near the mast top and add a string tension tie to the rear.|Keep the boom near horizontal.", "Make the tip pulley|Pierce the cap center, mount it on a low-friction pin, and add side guards.|Verify string stays in the groove.", "Install the winch|Support a pencil drum near the base with an outside crank and stop collar.|Align the string path with the mast.", "Route and hook the line|Wind neatly, pass over the tip pulley, and attach a closed hook.|Test with an empty paper cup.", "Balance the crane|Add rear mass until the unloaded base stays flat at full boom reach.|Do not exceed the safe counterweight limit.", "Lift and slew|Raise 50 grams through 20 cm, then rotate the base a quarter turn slowly.|Record base lift, boom deflection, and crank turns."
    ],
    math: math("Compare tipping moments", "moment = force × horizontal distance", ["Load force ≈ 0.49 N", "Reach = 0.20 m"], "moment = 0.49 × 0.20 = 0.098 N·m", "The load creates about 0.10 newton-metres of tipping moment.", "A counterweight farther behind the mast needs less force.", "Boom and crane masses also contribute moments."),
    test: test("Lift an empty cup 20 cm before adding weight.", "The crane lifts 50 grams, rotates 90 degrees, and keeps every base foot in contact.", "Lift height, boom deflection, and base-foot lift.", "the load's horizontal reach", "load mass, base, counterweight, string, boom, and lift height", ["10 cm reach", "15 cm reach", "20 cm reach"]),
    failures: ["The crane tips forward|Load moment exceeds base resistance|Watch rear foot during a low load|Reduce reach or add safe rear ballast", "The boom bends|Section is shallow or tie loose|Measure tip deflection unloaded and loaded|Laminate boom and tension the tie", "String leaves pulley|Side guards or alignment are poor|Raise empty cup slowly|Add guards and center the line", "The winch unwinds|No holding method is present|Support load and release briefly|Add a simple ratchet or always hold crank"],
    tuning: "Shorter reach improves capacity and stability but reduces workspace. Strengthen the boom as a deep folded section and use the smallest counterweight that keeps a safe margin.",
    extensions: ["Easier|Fixed-boom lift|Skip base rotation and lift an empty cup.", "Performance|Two-part line|Add a moving pulley and compare input force.", "Advanced|Load chart|Graph safe mass versus boom reach."],
    related: ["pulley-elevator", "block-and-tackle-hoist", "mechanical-advantage-lift-challenge"],
    builderMoment: "The crane lifted the load. The rear foot briefly considered joining it."
  },
  {
    number: 72,
    title: "Clothespin Grabber",
    slug: "clothespin-grabber",
    difficulty: "Beginner",
    ageRange: "10-15",
    estimatedTime: "30-50 min",
    timeMinutes: 50,
    maxCost: 6,
    description: "Extend a clothespin's squeeze action through lightweight arms and soft jaws to pick up small objects.",
    hook: "A clothespin already contains a pivot, spring, handles, and jaws. Extending its levers changes reach, travel, and force, making it a compact mechanical design study.",
    outcome: "The grabber picks up three different lightweight objects, holds each for five seconds, and releases without the extension arms twisting off.",
    concepts: ["First-class lever", "Spring force", "Grip"],
    input: "hand squeeze at clothespin handles",
    output: "opening or closing at extended jaws",
    motion: "angular squeeze-to-angular jaw motion",
    losses: ["extension flex", "pivot friction", "pad slip", "misaligned arms"],
    principleName: "Lever-arm tradeoff",
    principle: "Moving a contact farther from the pivot increases jaw travel for a given angle but reduces available force at that point. The clothespin spring supplies the restoring force.",
    observe: "Compare grip near the original jaw tip with grip at the end of a long extension.",
    materials: householdMaterials("1|wooden spring clothespin|Provide pivot and spring", "2|craft sticks or folded-card arms about 15 cm|Extend reach", "2|foam squares|Create soft jaw pads", "4|small rubber bands or tape wraps|Secure arms", "3|light test objects with different shapes|Evaluate grip"),
    alternative: "Use a binder clip with covered handles when a clothespin is unavailable.",
    hazard: "Keep the spring clip away from fingers and faces, and use only lightweight objects.",
    accessNote: "Add wide foam handle sleeves and larger jaw pads.",
    steps: ["Inspect the clothespin|Open and close it ten times and check the spring is seated.|Discard cracked wood or rusty springs.", "Prepare equal arms|Cut or fold two matching 15 cm extensions and mark the clothespin overlap.|Keep both straight.", "Attach the extensions|Secure one arm to each jaw with tape plus a rubber-band wrap.|Align them in the same plane.", "Add jaw pads|Place foam at the extension tips facing each other.|Keep pad centers at equal distance from the pivot.", "Check open clearance|Squeeze handles and confirm extensions separate without crossing.|Trim any rubbing edge.", "Test near and far grip|Hold one object near the original jaw, then at the extended tips.|Compare hand effort and slip.", "Try three shapes|Pick up a paper ball, empty cup, and marker over a tray.|Hold each for five seconds.", "Tune the tips|Change pad texture or angle while keeping arms the same.|Repeat the object that slipped most."
    ],
    math: math("Estimate tip force", "tip force = spring moment / tip distance", ["Spring moment = 0.06 N·m", "Tip distance = 0.15 m"], "tip force = 0.06/0.15 = 0.4 N", "The ideal extension-tip force is about 0.4 newtons.", "A shorter extension would give more force but less reach.", "Arm flex and jaw angle reduce real force."),
    test: test("Operate the empty grabber ten times after securing the arms.", "It holds three lightweight objects for five seconds and returns fully.", "Successful pickups, hold time, and tip opening.", "the jaw-pad texture", "clothespin, arm length, objects, pickup position, and hold time", ["bare card", "foam", "rubberized paper"]),
    failures: ["Arms twist sideways|Attachments are loose or off-center|Open slowly and view from above|Realign and add a second wrap", "Objects slip|Pads are smooth or not parallel|Close gently around the object|Add foam and angle pads", "The grabber will not open far|Extensions collide near the pivot|Operate empty and mark contact|Trim or offset the arms", "The clothespin spring shifts|Extensions overload or mounting covers spring|Inspect after each trial|Reduce mass and clear the spring"],
    tuning: "Long extensions increase reach and tip travel but reduce force and stiffness. Improve pad contact before shortening the arms, then choose the minimum length that meets the reach goal.",
    extensions: ["Easier|Short soft jaws|Add only foam pads to the original clothespin.", "Performance|Curved jaws|Shape tips for cups versus round objects.", "Creative|Sorting task|Move ten objects into bins by shape."],
    related: ["linkage-grabber-arm", "cup-stacking-mechanical-hand", "parallel-jaw-gripper"],
    builderMoment: "The clothespin gained reach and immediately learned about leverage."
  },
  {
    number: 73,
    title: "Craft-Stick Scissor Lift",
    slug: "craft-stick-scissor-lift",
    difficulty: "Intermediate",
    ageRange: "11-17",
    estimatedTime: "75-110 min",
    timeMinutes: 110,
    maxCost: 10,
    description: "Raise a small platform with crossed craft-stick pairs and a hand-driven input that changes their opening angle.",
    hook: "Crossed links convert horizontal motion at the base into vertical motion at the platform. Near the collapsed position, the lift can demand a lot of input force and good alignment.",
    outcome: "The platform rises at least 15 cm, stays within 10 degrees of level, and lifts a 50-gram load without a pivot separating.",
    concepts: ["Scissor linkage", "Mechanical advantage", "Stability"],
    input: "horizontal motion between lower pivots",
    output: "vertical platform lift",
    motion: "linear input-to-vertical translation",
    losses: ["pivot friction", "link bending", "slot rubbing", "platform tilt"],
    principleName: "Scissor geometry",
    principle: "Crossed equal links form changing diamonds. Pulling lower pivots together increases link angle and raises the top, while stacked stages multiply height and alignment demands.",
    observe: "Measure input distance and platform height at several angles instead of assuming a constant ratio.",
    materials: householdMaterials("16|equal craft sticks|Form four crossed pairs", "9|paper fasteners or small bolts|Create center and end pivots", "1|12 × 15 cm cardboard base|Anchor the lift", "1|12 × 15 cm platform|Carry a safe load", "2|straight guide slots|Allow moving end pivots", "1|50-gram test mass|Provide load"),
    alternative: "Use doubled cardboard strips with punched holes instead of craft sticks.",
    hazard: "Keep fingers away from folding diamonds and never use the lift for hands, people, or heavy objects.",
    accessNote: "Use a large threaded knob or pull handle and color-code fixed versus sliding pivots.",
    steps: ["Pair and mark sticks|Stack equal sticks and mark center and end holes from one template.|An adult should pierce aligned holes.", "Build four X units|Join each pair at its center with free pivots.|Check equal arm lengths on both sides.", "Connect the first side chain|Join two X units end to end to make a two-level scissor side.|Keep links in alternating depth planes.", "Build the matching side|Duplicate the chain and overlay it with the first.|Correct any unequal center distance.", "Mount fixed base pivots|Attach one lower end on each side to the base.|Place the opposite lower ends in parallel slots.", "Attach the platform|Fix one upper end on each side and guide the opposite ends in top slots.|Keep left and right sides synchronized with crossbars.", "Add the input handle|Connect the sliding lower pivots to a pull bar or slow screw.|Add stops before links fully flatten or straighten.", "Lift and load|Raise empty through the full range, then add 50 grams at center.|Measure height, level angle, and input travel."
    ],
    math: math("Estimate one-stage height", "height = 2L × sin(θ)", ["Half-link length L = 60 mm", "Link angle θ = 30°", "sin(30°) = 0.5"], "height = 2 × 60 × 0.5 = 60 mm", "One ideal scissor diamond is 60 mm high at 30 degrees.", "More stages add height but also flexibility.", "Joint offsets and slot geometry change the real value."),
    test: test("Raise the empty platform from its lowest safe position.", "It reaches 15 cm, stays within 10 degrees of level, and carries 50 grams.", "Platform height, level angle, and input distance.", "the number of scissor stages", "link length, base, platform, load position, input, and stops", ["one stage", "two stages", "two stages with centered load"]),
    failures: ["The platform tilts|Left and right link chains differ or move separately|Measure both side heights|Match geometry and add crossbars", "The lift locks low|Links start too flat or input lacks force|Raise slightly by hand and test|Set a higher minimum stop", "A pivot tears out|Hole is close to an edge or overtight|Inspect whitening around holes|Reinforce ends and loosen pivots", "Slots bind|Moving pins tilt or slots differ|Move empty and watch each slider|Widen and align guide slots"],
    tuning: "Avoid near-flat and near-straight extremes, where force or locking becomes severe. More stages increase height but lower stiffness; cross-connect both sides before adding load.",
    extensions: ["Easier|Single-stage lift|Build one X pair per side with an empty platform.", "Performance|Lead-screw input|Add a slow threaded drive to control height.", "Advanced|Force curve|Measure input force at several platform heights."],
    related: ["water-hydraulic-lift", "mechanical-advantage-lift-challenge", "toggle-clamp"],
    builderMoment: "The platform rose beautifully. The left scissor side arrived half a second later."
  },
  {
    number: 74,
    title: "Household Balance Scale",
    slug: "household-balance-scale",
    difficulty: "Beginner",
    ageRange: "10-15",
    estimatedTime: "35-55 min",
    timeMinutes: 55,
    maxCost: 5,
    description: "Compare unknown masses with a level beam, equal arm lengths, hanging cups, and simple calibration marks.",
    hook: "A balance does not need a numbered spring. Equal masses at equal distances create equal moments, so the beam settles level when both sides match.",
    outcome: "The empty beam balances within 5 degrees of level and correctly identifies equal versus unequal sample masses in five comparison trials.",
    concepts: ["Moments", "Equilibrium", "Calibration"],
    input: "gravity forces from two sample masses",
    output: "beam angle showing comparison",
    motion: "static force difference-to-angular deflection",
    losses: ["pivot friction", "unequal cup mass", "off-center strings", "beam flex"],
    principleName: "Rotational equilibrium",
    principle: "A beam balances when clockwise and counterclockwise moments about the pivot are equal. Equal arm lengths make equal mass the level condition.",
    observe: "Move the same mass closer to the center and watch its turning effect decrease.",
    materials: householdMaterials("1|30 cm ruler or straight cardboard beam|Provide equal lever arms", "1|pencil or skewer pivot|Support the center", "2|identical paper cups|Hold samples", "4|equal string lengths|Suspend cups", "1|cardboard stand and pointer scale|Show beam angle", "20|equal washers or coins|Calibrate comparisons"),
    alternative: "Use two identical reusable containers and dry beans as reference masses.",
    hazard: "Keep loads light, cover sharp skewer ends, and catch falling samples in a tray.",
    accessNote: "Add a long high-contrast pointer and tactile center and equal-arm marks.",
    steps: ["Build the stable stand|Brace two vertical supports around the pivot height.|Add a wide base that does not rock.", "Find the beam center|Measure and mark the midpoint, then make one centered pivot hole.|Check equal arm lengths to cup points.", "Hang the empty beam|Support it on a low-friction pivot and add a pointer at center.|Observe which side drops before adding cups.", "Make matched cup hangers|Punch equal holes in identical cups and attach equal string loops.|Hang them at matching beam marks.", "Zero the balance|Trim string or add tiny paper tabs until empty cups settle level.|Mark the zero pointer position.", "Calibrate with equal masses|Place five equal washers in each cup and wait for settling.|Confirm the pointer returns near zero.", "Run comparison trials|Hide different washer counts and predict heavier, lighter, or equal.|Record five outcomes.", "Explore arm length|Move one cup inward while keeping masses equal.|Explain the new imbalance using moments."
    ],
    math: math("Balance unequal distances", "mass₁ × distance₁ = mass₂ × distance₂", ["Mass₁ = 40 g at 10 cm", "Distance₂ = 20 cm"], "mass₂ = 40 × 10/20 = 20 g", "Twenty grams at 20 cm balances forty grams at 10 cm.", "Distance can trade against force in moment equilibrium.", "Pivot friction and beam mass affect precision."),
    test: test("Balance the two empty cups before comparing samples.", "The pointer stays within 5 degrees of zero for equal masses and identifies all five comparisons correctly.", "Pointer angle and correct comparison count.", "the sample mass difference", "beam, arm lengths, cups, strings, stand, and settling time", ["equal samples", "one-washer difference", "three-washer difference"]),
    failures: ["The empty scale leans|Beam, strings, or cups are unequal|Swap cups between sides|Re-zero with matching parts", "The beam sticks|Pivot friction is high|Tap lightly and watch whether it settles differently|Use a smoother centered pivot", "Cups swing too long|Strings are long or test is disturbed|Wait and shield from airflow|Shorten equal strings", "Results change after moving cups|Distances are no longer equal|Measure pivot-to-string centers|Reset symmetric marks"],
    tuning: "A low-friction pivot improves sensitivity but also increases swinging. Use equal lightweight cups, measure from the pivot center, and allow consistent settling time.",
    extensions: ["Easier|Heavy-light sorter|Compare clearly different objects.", "Performance|Smallest detectable difference|Find the minimum washer change that reliably moves the pointer.", "Advanced|Unequal-arm scale|Calibrate mass from known arm positions."],
    related: ["center-of-mass-balancing-sculpture", "friction-investigation-sled", "cardboard-coin-sorter"],
    builderMoment: "The masses were equal. The two paper cups had other data."
  },
  {
    number: 75,
    title: "Rolling Can Racer",
    slug: "rolling-can-racer",
    difficulty: "Beginner",
    ageRange: "10-16",
    estimatedTime: "35-55 min",
    timeMinutes: 55,
    maxCost: 5,
    description: "Hide a twisted rubber-band weight inside a round container and use stored energy to roll the can forward.",
    hook: "The can looks like it rolls by itself. Inside, a hanging mass twists a rubber band as the shell moves, storing and returning energy through the axle holes.",
    outcome: "The sealed racer rolls at least 1 metre along a clear lane, keeps all internal parts contained, and repeats three runs without the band detaching.",
    concepts: ["Elastic energy", "Rotational motion", "Center of mass"],
    input: "pre-rolling that twists an internal rubber band",
    output: "self-driven can rotation",
    motion: "stored elastic twist-to-rolling translation",
    losses: ["axle-hole friction", "internal mass rubbing", "shell slip", "band hysteresis"],
    principleName: "Internal elastic drive",
    principle: "Rolling the shell twists a rubber band around an off-axis internal mass. When released, the band applies torque to the container while the mass resists rotating with it.",
    observe: "Listen for internal rubbing and compare travel after different numbers of preload turns.",
    materials: householdMaterials("1|clean round oatmeal can or lidded plastic cylinder|Form the rolling shell", "1|long rubber band in good condition|Store twist energy", "2|large washers tied together under 40 g|Provide internal inertial mass", "2|pencils or dowels through lid centers|Anchor band ends", "2|secure end lids and strong tape|Contain every internal part"),
    alternative: "Use a sturdy lidded food container with both ends fully closed and no sharp metal edges.",
    hazard: "Use a non-glass container, fully seal both ends, wear eye protection, and keep the lane clear of people.",
    accessNote: "Use a large container, a start cradle, and tactile preload marks around the rim.",
    steps: ["Inspect the container|Confirm both ends close securely and no metal edge is exposed.|Reject cracked or sharp containers.", "Mark axle centers|Find and mark the center of both circular ends.|An adult should make small reinforced holes.", "Prepare the internal mass|Tie two washers into a padded bundle below 40 grams.|Attach the bundle to the rubber-band midpoint so it hangs freely.", "Thread the band|Pass one band end through each center hole and anchor it to an outside dowel.|Keep the mass centered inside.", "Seal both ends|Close lids, tape every seam, and cover external anchors.|Shake gently to confirm containment.", "Run a zero-preload roll|Place on a lane and confirm the shell rolls without severe wobble.|Listen for the mass hitting a wall.", "Store the energy|Roll the can backward through three measured turns while holding the lane.|Set it down without adding a push.", "Compare three trials|Test three, five, and seven safe preload turns.|Record distance, direction, and internal sounds."
    ],
    math: math("Find rolling distance", "distance = turns × π × diameter", ["Can diameter = 0.10 m", "Can turns = 5"], "distance = 5 × 3.14 × 0.10 = 1.57 m", "Five shell rotations correspond to about 1.57 metres without slip.", "Stored energy may produce fewer or more visible rotations after release depending on preload.", "Floor slip and internal rubbing change travel."),
    test: test("Roll the sealed can once by hand before adding stored twist.", "It travels at least 1 metre and all parts remain securely contained.", "Distance, shell rotations, path drift, and internal impacts.", "the preload turn count", "can, band, mass, surface, lane, and release method", ["3 turns", "5 turns", "7 turns if the band remains safe"]),
    failures: ["The can does not move|Band is not twisting or mass rotates with shell|Open only after securing the can and inspect|Retie the mass off-axis and band midpoint", "It wobbles badly|Holes are off-center or mass hits a wall|Roll with no preload|Recenter holes and shorten the mass hanger", "Travel is short|Internal rubbing or shell slip is high|Listen during release|Center the mass and choose a grippier floor", "A lid loosens|Tape or fit is inadequate|Inspect after every low-turn trial|Stop and reseal before any further use"],
    tuning: "Center the axle holes and keep the internal mass clear before adding more preload. Extra turns can increase travel only until band friction, shell slip, or safety limits dominate.",
    extensions: ["Easier|Observation window model|Use a transparent safe container to watch the mass.", "Performance|Mass comparison|Test two contained masses under 40 grams.", "Creative|Target race|Tune preload to stop nearest a marked line."],
    related: ["rubber-band-car", "balloon-powered-car", "gravity-marble-timer"],
    builderMoment: "The can rolled forward, paused, and held a private meeting with its internal washer."
  },
  {
    number: 76,
    title: "Rubber-Band Paddle Boat",
    slug: "rubber-band-paddle-boat",
    difficulty: "Beginner",
    ageRange: "10-16",
    estimatedTime: "40-65 min",
    timeMinutes: 65,
    maxCost: 6,
    description: "Turn a twisted rubber band into paddle rotation and tune a lightweight tray boat for straight, repeatable travel.",
    hook: "A rubber band stores twist, the paddle pushes water backward, and the hull moves forward. Paddle depth and hull symmetry determine whether the boat cruises or performs an unexpected circle.",
    outcome: "The boat remains upright, releases without a hand push, and travels at least 1 metre through a shallow test tub in three repeatable trials.",
    concepts: ["Elastic potential energy", "Fluid thrust", "Stability"],
    input: "twist stored in a rubber band",
    output: "paddle rotation and forward boat motion",
    motion: "elastic twist-to-rotary-to-linear motion",
    losses: ["water drag", "paddle slip", "shaft rubbing", "hull yaw"],
    principleName: "Paddle-wheel thrust",
    principle: "The rotating paddle accelerates water backward. The water applies a forward reaction force to the boat while the wide hull resists rolling.",
    observe: "Mark one paddle blade and compare travel when the blade enters one-quarter versus one-half of its height.",
    materials: householdMaterials("1|clean foam food tray about 15 × 25 cm|Form a buoyant hull", "2|craft sticks about 12 cm|Hold the paddle axle", "1|straight skewer with covered ends|Carry the paddle", "2|5 × 8 cm waterproof-card paddles|Push water", "1|long rubber band in good condition|Store rotational energy", "1|shallow plastic tub at least 1.2 m long|Create a contained test course"),
    alternative: "Use a folded foil tray with taped edges or two cork pontoons joined by a cardboard deck.",
    hazard: "Wear eye protection while winding, test only in shallow contained water, and dry spills immediately; this is not a person-carrying boat.",
    accessNote: "Add a large winding handle and use a partner to steady the hull while another builder counts turns.",
    steps: ["Shape the hull|Trim the tray symmetrically and mark its centerline.|Keep the stern wide enough for the paddle.", "Build axle towers|Tape one craft stick upright on each rear side.|Measure equal heights above the waterline.", "Install the paddle axle|Make centered holes with adult help and slide the covered skewer through.|Confirm it turns without scraping the hull.", "Make a balanced paddle|Cross two waterproof cards at their centers and tape them squarely to the axle.|Keep all four blade areas equal.", "Connect the rubber band|Loop the band between the axle center and a bow anchor.|Guide it clear of the deck and water.", "Float-test without winding|Add small tape ballast until the hull sits level and the paddle barely enters the water.|Check for leaks or tilting.", "Run low-energy trials|Wind five turns, set the boat at the start line, and release without pushing.|Measure distance and sideways drift.", "Tune paddle depth|Compare shallow, medium, and deep axle heights with equal winding.|Dry and inspect the band between trials."],
    math: math("Estimate paddle tip travel", "tip distance = rotations × 2 × π × radius", ["Paddle radius = 0.04 m", "Rotations = 8"], "distance = 8 × 2 × 3.14 × 0.04 = 2.01 m", "The blade tips move through about 2 metres of circular path.", "Water motion is much less because blades slip through the water.", "This ideal path ignores drag and band speed changes."),
    test: test("Float the unwound boat for thirty seconds before powering it.", "The hull stays level and travels at least 1 metre without contacting the tub sides.", "Distance, travel time, drift, and paddle rotations.", "paddle immersion depth", "hull, band turns, water depth, start point, and release", ["one-quarter blade depth", "one-half blade depth", "three-quarter blade depth"]),
    failures: ["The boat turns sharply|Paddle or hull is asymmetric|Wind slowly and view from behind|Center the axle and match blade area", "The paddle spins but travel is short|Blades are too shallow or slip excessively|Watch the water wake|Lower the axle slightly", "The stern sinks|Axle towers or band pull add rear load|Float without the paddle|Move supports forward or add bow ballast", "The axle stops early|Band rubs the deck or towers|Turn it by hand while dry|Raise the guide and widen bearing clearance"],
    tuning: "Start with straight alignment and a level hull. Deeper blades can create more thrust, but they also add drag and may pull the stern down.",
    extensions: ["Easier|Two-blade paddle|Use one crossed strip and five winding turns.", "Performance|Straight-line rudder|Add a small centered fin and compare drift.", "Advanced|Energy study|Graph distance against safe winding turns and identify diminishing returns."],
    related: ["rubber-band-car", "balloon-hovercraft", "wind-powered-sail-car"],
    builderMoment: "The paddle boat discovered hydrodynamics and immediately requested a larger test tub."
  },
  {
    number: 77,
    title: "Balloon Hovercraft",
    slug: "balloon-hovercraft",
    difficulty: "Beginner",
    ageRange: "10-16",
    estimatedTime: "30-50 min",
    timeMinutes: 50,
    maxCost: 5,
    description: "Release balloon air beneath a lightweight disk to create a thin cushion that reduces sliding friction.",
    hook: "A smooth disk normally drags against the table. Feed air underneath and the surfaces separate slightly, turning sticky sliding into a low-friction glide.",
    outcome: "The hovercraft glides at least 75 cm from a gentle level release and repeats three runs without its balloon or nozzle detaching.",
    concepts: ["Air pressure", "Friction", "Flow rate"],
    input: "pressurized air from an inflated balloon",
    output: "a supporting air film and horizontal glide",
    motion: "airflow-to-low-friction translation",
    losses: ["air leakage", "surface roughness", "disk tilt", "nozzle restriction"],
    principleName: "Air-film lubrication",
    principle: "Air escaping beneath the disk raises it by a tiny amount and reduces direct contact. The lift is small, but lowering friction makes a gentle push last longer.",
    observe: "Compare how quickly the disk stops with the nozzle closed and open on the same tabletop.",
    materials: householdMaterials("1|old compact disc or 12 cm smooth cardboard disk|Spread the air film", "1|push-pull bottle-cap nozzle or short tube|Meter airflow", "1|balloon|Store air", "1|reusable putty or tape|Seal the nozzle joint", "1|smooth level tabletop at least 1 m long|Provide a test surface"),
    alternative: "Use a smooth plastic lid with a centered adult-made hole instead of a disc.",
    hazard: "Check latex allergies, discard torn balloons, keep fragments away from young children, and never place the inflated balloon near a face.",
    accessNote: "Use a large pull tab on the nozzle and a marked release rail so the builder can start the craft without pinching the balloon.",
    steps: ["Prepare the base|Inspect the disk and cover any sharp center edge with tape.|Mark the geometric center.", "Make the air port|Center the nozzle over the hole and seal its entire rim.|Keep the opening vertical.", "Check the seal|Blow gently through the nozzle while covering the bottom opening.|Listen and feel for side leaks.", "Attach the balloon|Stretch the neck over the closed nozzle without tearing it.|Support the balloon so it does not tip the disk.", "Set a control run|Slide the uninflated craft from a fixed release mark.|Measure stopping distance.", "Inflate safely|Remove the balloon, inflate it, pinch the neck, and reconnect with the nozzle closed.|Keep the opening pointed away from faces.", "Release the air film|Place the craft level, open the nozzle, and give the same gentle release.|Measure distance and time.", "Compare flow settings|Test three nozzle openings with equal balloon circumference.|Record glide distance before reinflating."],
    math: math("Compare friction reduction", "distance gain = air-on distance / air-off distance", ["Air off = 0.20 m", "Air on = 0.90 m"], "gain = 0.90 / 0.20 = 4.5", "The air-on craft glides 4.5 times farther in this test.", "Longer glide suggests lower effective friction.", "Release force and balloon pressure are approximate."),
    test: test("Run the disk once with no air as a control.", "With air on, it glides at least 75 cm and farther than the control.", "Glide distance, time, and path curvature.", "nozzle opening", "disk, table, balloon circumference, release ramp, and start point", ["small opening", "medium opening", "fully open"]),
    failures: ["The craft does not lift|Air escapes around the nozzle|Feel around the seal|Reseal the full rim", "It tips and drags|Balloon or nozzle is off-center|View from table height|Recenter the mass and port", "Air empties instantly|Opening is too large|Time the discharge|Restrict the nozzle", "The craft curves|Base is warped or table is uneven|Rotate the disk and repeat|Flatten the base or change surface"],
    tuning: "A centered, airtight port matters more than maximum balloon size. Faster airflow can create more lift but shortens the useful glide time.",
    extensions: ["Easier|On-and-off comparison|Use one nozzle opening and measure five runs.", "Performance|Skirt experiment|Add a loose paper ring beneath the edge and compare stability.", "Creative|Hover target|Tune airflow to stop inside a taped landing zone."],
    related: ["balloon-powered-car", "rubber-band-paddle-boat", "friction-investigation-sled"],
    builderMoment: "The hovercraft rose by a millimetre and gained the confidence of an aircraft carrier."
  },
  {
    number: 78,
    title: "Magnetic Maze",
    slug: "magnetic-maze",
    difficulty: "Beginner",
    ageRange: "10-16",
    estimatedTime: "35-60 min",
    timeMinutes: 60,
    maxCost: 8,
    description: "Guide a steel token through a covered maze using a safely enclosed magnet beneath the board.",
    hook: "The controller never touches the token. Magnetic force acts through cardboard, while distance, barriers, and surface friction set the difficulty.",
    outcome: "A sealed steel token completes the maze in under 90 seconds without leaving the track or exposing a loose magnet.",
    concepts: ["Magnetic force", "Friction", "Control systems"],
    input: "hand motion of an enclosed magnet below the board",
    output: "controlled steel-token motion through the maze",
    motion: "remote hand translation-to-token translation",
    losses: ["board thickness", "surface friction", "magnet offset", "wall impacts"],
    principleName: "Magnetic force through materials",
    principle: "A magnet attracts ferromagnetic steel through thin nonmagnetic cardboard. The force becomes weaker as the gap increases, so board thickness and token mass matter.",
    observe: "Stack paper under the token and find the greatest gap at which the controller still starts it moving.",
    materials: householdMaterials("1|25 × 35 cm corrugated-cardboard board|Support the maze", "8-12|2 cm-wide cardboard wall strips|Define paths", "1|large magnet permanently sealed in a taped card pouch|Act as controller", "1|large steel washer sealed between two card disks|Serve as token", "1|clear plastic sheet or mesh cover|Contain the token"),
    alternative: "Use a magnetic whiteboard eraser as the enclosed controller and a large steel jar lid as the token.",
    hazard: "Magnets can cause severe injury if swallowed; use only large, fully enclosed magnets under adult control and keep them away from medical devices and electronics.",
    accessNote: "Make paths at least 5 cm wide, add raised tactile wall labels, and attach the controller to a large handle.",
    steps: ["Plan the route|Draw one continuous 5 cm-wide path with a start, three turns, and finish.|Avoid narrow dead ends.", "Build the walls|Tape strips along both path edges and test token clearance.|Round inside corners to prevent trapping.", "Seal the token|Sandwich the steel washer between two card disks and tape every edge.|Make it too large to swallow.", "Enclose the controller|Seal the magnet inside a card pouch attached to a broad handle.|Inspect all seams before use.", "Add the top cover|Tape clear plastic over the wall tops with no token-sized gaps.|Leave one adult-access flap secured by tape.", "Calibrate the gap|Move the controller beneath the start and confirm the token follows.|Add a thin spacer if attraction is too abrupt.", "Run a baseline maze|Time one slow completion without lifting or shaking the board.|Record where control is lost.", "Tune the challenge|Change one turn radius or add one nonmagnetic obstacle.|Repeat three timed trials."],
    math: math("Measure completion improvement", "percent improvement = (first time - new time) / first time × 100%", ["First time = 80 s", "New time = 60 s"], "improvement = (80 - 60) / 80 × 100% = 25%", "The new run is 25 percent faster.", "Practice and design changes both affect time.", "Timing reaction adds small uncertainty."),
    test: test("Confirm the token follows over a straight 20 cm path before using the maze.", "The enclosed token reaches the finish in under 90 seconds during three trials.", "Completion time, wall contacts, and control losses.", "board-to-controller gap", "maze, token, magnet, operator, and start method", ["no spacer", "one card spacer", "two card spacers"]),
    failures: ["The token will not start|Gap is too large or token is not steel|Test attraction with the board open|Use a thinner board or verified steel washer", "The token jumps over walls|Attraction is too abrupt|Move the controller slowly at a corner|Add a spacer or taller walls", "It sticks at corners|Wall radius is tight or surface rough|Push the token manually|Round corners and smooth tape", "The controller detaches|Pouch seam or handle is weak|Inspect before every run|Stop and reseal with a larger pouch"],
    tuning: "The best maze balances reliable attraction with enough friction and distance to require control. Stronger is not always better; a small spacer often makes movement smoother.",
    extensions: ["Easier|Wide-route maze|Use two turns and 7 cm paths.", "Performance|Precision course|Add numbered checkpoints and count wall contacts.", "Advanced|Field mapping|Measure the maximum pickup gap at several controller offsets."],
    related: ["tilt-alarm", "center-of-mass-balancing-sculpture", "classroom-rescue-device"],
    builderMoment: "The token followed the magnet faithfully until corner three presented a compelling alternative."
  },
  {
    number: 79,
    title: "Gravity Marble Timer",
    slug: "gravity-marble-timer",
    difficulty: "Intermediate",
    ageRange: "11-17",
    estimatedTime: "60-90 min",
    timeMinutes: 90,
    maxCost: 8,
    description: "Create a repeatable rolling timer by tuning a marble path with slopes, gates, and energy-losing turns.",
    hook: "Gravity supplies the energy, but the path controls how quickly the marble spends it. Long shallow slopes, banked turns, and deliberate obstacles make time a design variable.",
    outcome: "One released marble reaches the finish in a target time of 8 to 12 seconds with less than 10 percent spread across five trials.",
    concepts: ["Gravitational potential energy", "Rolling motion", "Repeatability"],
    input: "marble release from a fixed height",
    output: "a delayed arrival at the finish gate",
    motion: "gravitational drop-to-controlled rolling motion",
    losses: ["rolling friction", "wall impacts", "track flex", "release variation"],
    principleName: "Controlled energy descent",
    principle: "The marble starts with gravitational potential energy. A longer, shallower route and controlled impacts spread the energy release over more time without stopping motion.",
    observe: "Mark three timing points and identify which track segment contributes the most delay.",
    materials: householdMaterials("1|marble at least 16 mm wide|Provide rolling mass", "6|paper tubes split lengthwise|Form track channels", "1|60 × 90 cm backing board|Hold the route", "1|cardboard release gate|Create a repeatable start", "1|catch cup with padded bottom|Stop the marble safely", "1|stopwatch|Measure travel time"),
    alternative: "Use folded cardstock V-tracks and a wooden ball too large to swallow.",
    hazard: "Contain the marble at every edge, keep the track below shoulder height, and store small balls securely after the activity.",
    accessNote: "Use an oversized ball and track, high-contrast timing markers, and a lever-operated release gate.",
    steps: ["Set the target|Choose a finish time between 8 and 12 seconds and mark start and finish heights.|Keep total drop below 60 cm.", "Build a release gate|Make a sliding card that holds the marble without squeezing it.|Add a handle for consistent removal.", "Lay the first descent|Tape a shallow channel from the start and add side walls at least one radius high.|Roll once before adding the next section.", "Add two switchbacks|Use broad banked curves that redirect the marble without a sharp collision.|Support both ends and centers.", "Create a delay section|Add a gentle zigzag or wide spiral while preserving downhill slope.|Check every joint for upward lips.", "Install the catch cup|Pad the bottom and connect track walls continuously into it.|Shake the board gently to confirm secure joints.", "Time five trials|Release without pushing and record split times at three marks.|Reset the same marble and board angle.", "Tune one segment|Lower one slope or lengthen one curve to reach the target.|Repeat five trials and compare spread."],
    math: math("Calculate timing spread", "spread = (maximum time - minimum time) / average time × 100%", ["Times = 9.4, 9.8, 9.6, 9.5, 9.7 s", "Average = 9.6 s"], "spread = (9.8 - 9.4) / 9.6 × 100% = 4.2%", "The timer varies by about 4.2 percent across five runs.", "A smaller spread means better repeatability.", "Human timing and release friction add uncertainty."),
    test: test("Roll one low-speed trial through each new section before completing the route.", "Five runs average 8 to 12 seconds with less than 10 percent spread.", "Total time, three split times, stops, and wall contacts.", "one track slope", "marble, release, board angle, route, timing method, and room", ["baseline slope", "2 cm lower", "2 cm higher"]),
    failures: ["The marble stops|A joint rises or slope is flat|Roll slowly and mark the stop|Smooth the joint or increase drop slightly", "It leaves the track|Turn is too tight or wall too low|Watch from above at the exit|Widen, bank, and raise the wall", "Times vary widely|Gate rubs or track flexes|Film the release and first section|Stiffen supports and loosen the gate", "The run is too fast|Too much height is spent early|Compare split times|Flatten the fastest segment and lengthen the path"],
    tuning: "Tune the segment with the largest timing effect first. Adding obstacles may slow the marble, but hard impacts usually increase variability and derailment risk.",
    extensions: ["Easier|Five-second timer|Use one switchback and three trials.", "Performance|Ten-second target|Score each run by absolute error from 10.0 seconds.", "Advanced|Split-time model|Predict total time from measured segment averages."],
    related: ["marble-run-challenge", "slowest-marble-track", "cardboard-marble-elevator"],
    builderMoment: "The timer hit exactly ten seconds once and has been discussing sample size ever since."
  },
  {
    number: 80,
    title: "Chain Reaction Machine",
    slug: "chain-reaction-machine",
    difficulty: "Intermediate",
    ageRange: "10-18",
    estimatedTime: "75-120 min",
    timeMinutes: 120,
    maxCost: 10,
    description: "Link ramps, levers, rolling objects, and falling cups into a reliable multi-stage machine that completes one simple task.",
    hook: "Each stage must produce enough motion to trigger the next, but not so much that it skips ahead. Reliability comes from generous targets, clean energy transfers, and testing interfaces one at a time.",
    outcome: "A five-stage sequence starts from one action and completes its final task on at least four of five full runs.",
    concepts: ["Energy transfer", "Cause and effect", "Reliability engineering"],
    input: "one hand release at the first stage",
    output: "completion of a visible final task",
    motion: "linked rolling, falling, rotating, and lever motions",
    losses: ["impact misalignment", "surface friction", "flexing triggers", "timing variation"],
    principleName: "Sequential energy transfer",
    principle: "Each stage receives energy, transforms it, and passes enough useful output to the next trigger. Interfaces between stages usually fail before individual mechanisms do.",
    observe: "Label every handoff and note whether the incoming motion reaches the center of its intended target.",
    materials: householdMaterials("12-20|dominoes or folded-card standups|Create one falling stage", "2|paper tubes or cardboard ramps|Guide rolling objects", "2|ping-pong balls or large wooden balls|Carry motion safely", "2|cups and string|Provide falling or lifting actions", "3|rulers, spoons, or craft sticks|Create levers", "1|paper flag or small bell|Show the final task"),
    alternative: "Use books, blocks, recycled packaging, and rolled paper while avoiding breakable or heavy objects.",
    hazard: "Keep the machine on the floor or a low table, avoid projectiles and glass, and keep every moving object contained inside the test area.",
    accessNote: "Assign each builder one stage, use numbered high-contrast handoff zones, and include a large accessible start control.",
    steps: ["Choose the final task|Pick a safe visible finish such as raising a paper flag.|Work backward to decide the final trigger.", "Map five stages|Draw boxes for release, ramp, dominoes, lever, and flag.|Write the required output at each handoff.", "Build stage five first|Make the final task operate with a deliberate hand trigger.|Measure the motion needed to activate it.", "Add stage four|Build a lever or falling cup that reliably supplies that motion.|Test the two-stage pair five times.", "Build the middle stages|Add one rolling and one falling action with containment walls.|Test each new interface before continuing.", "Create the start|Use a gate or upright block that begins with one clear hand action.|Prevent vibration from triggering later stages early.", "Run interface tests|Trigger each stage immediately before its handoff five times.|Widen targets that miss more than once.", "Run five complete trials|Reset from a checklist and record the first failed stage each time.|Change only the least reliable interface."],
    math: math("Find system reliability", "system reliability = successful full runs / total runs × 100%", ["Successful runs = 4", "Total runs = 5"], "reliability = 4/5 × 100% = 80%", "The full machine is 80 percent reliable in this sample.", "One weak handoff can dominate the total result.", "Five runs are useful for tuning but not a long-term reliability claim."),
    test: test("Test each adjacent pair of stages before the first complete run.", "At least four of five complete runs reach the final task from one start action.", "First failed stage, full-run time, and reset errors.", "target width at the weakest handoff", "stage order, objects, starting energy, surface, and reset checklist", ["baseline target", "target 2 cm wider", "target 4 cm wider"]),
    failures: ["A stage fires early|Vibration reaches an unstable trigger|Tap the table without starting|Widen bases and separate stages", "The ball misses a lever|Exit direction or target is too narrow|Run only that handoff five times|Add guide walls and enlarge the lever target", "Dominoes stop midway|Spacing or surface changes|Inspect the first gap after stopping|Use a spacing jig and flat surface", "Full runs vary|Reset positions are inconsistent|Photograph the ready state|Make a numbered reset checklist and alignment marks"],
    tuning: "Improve the least reliable handoff, not the most dramatic stage. Larger targets and lower trigger thresholds improve reliability but can increase accidental starts.",
    extensions: ["Easier|Three-stage machine|Use a ramp, lever, and flag.", "Performance|Ninety-percent target|Reach nine successful runs out of ten.", "Creative|Timed story|Make each safe stage reveal one part of a message."],
    related: ["rube-goldberg-switch", "mechanical-counter", "hand-crank-cardboard-automaton"],
    builderMoment: "Stages one through four were flawless. Stage five had not received the calendar invitation."
  },
  {
    number: 81,
    title: "Egg-Drop Capsule",
    slug: "egg-drop-capsule",
    difficulty: "Intermediate",
    ageRange: "11-18",
    estimatedTime: "60-100 min",
    timeMinutes: 100,
    maxCost: 8,
    description: "Protect a simulated fragile payload by increasing stopping time, controlling orientation, and testing from safe indoor heights.",
    hook: "A good capsule does not eliminate impact energy. It spreads the stopping process over more distance and time while keeping the payload away from hard edges.",
    outcome: "A plastic practice egg or sealed snack bag survives three 1.5-metre indoor drops with no leak, shell opening, or capsule part leaving the landing zone.",
    concepts: ["Impulse", "Energy absorption", "Controlled testing"],
    input: "gravitational fall from a fixed height",
    output: "a longer, gentler payload stop",
    motion: "vertical fall-to-deformation and deceleration",
    losses: ["crumple deformation", "air drag", "payload shifting", "asymmetric landing"],
    principleName: "Impulse and stopping time",
    principle: "For the same change in momentum, increasing the time over which the payload stops lowers the average impact force. Crush zones and suspended supports extend that stop.",
    observe: "Film from the side and compare how far the outer capsule deforms before the payload stops moving.",
    materials: householdMaterials("1|plastic practice egg or sealed 50 mL water bag|Represent a fragile payload", "12|paper straws|Form a crush frame", "4|rubber bands|Suspend the payload", "2|sheets of scrap paper|Create crumple zones", "1|lightweight paper cup|Contain the payload", "1|large towel inside a taped landing zone|Catch the capsule"),
    alternative: "Use a tomato only with adult permission and a sealed secondary bag; a plastic egg is cleaner for repeated engineering tests.",
    hazard: "Use only a supervised indoor drop at or below 1.5 metres, clear the landing zone, and never drop from stairs, roofs, or over people.",
    accessNote: "Use a table-edge release gate, pre-cut straws, and team roles for measuring, releasing, observing, and inspecting.",
    steps: ["Define the payload|Weigh and inspect the sealed practice payload.|Mark any existing dents or leaks.", "Build a suspension cup|Make four opposite holes near the cup rim and thread rubber bands through.|Center the payload without squeezing it.", "Create a straw frame|Tape straws into a cube larger than the cup on every side.|Add diagonal braces to stop collapse during handling.", "Suspend the cup|Connect the cup bands to frame corners so it floats with 3 cm clearance.|Check every direction.", "Add crush zones|Attach loose paper cones to the bottom and side corners.|Keep them replaceable after a drop.", "Set the landing zone|Tape a 60 cm square on the floor and place a flat towel inside.|Choose a safe 0.5-metre first height.", "Run staged drops|Test at 0.5, 1.0, then 1.5 metres only after inspection passes.|Release without throwing or spinning.", "Inspect and improve|Measure deformation and payload movement after each drop.|Replace crushed parts before three final trials."],
    math: math("Estimate starting potential energy", "energy = mass × g × height", ["Mass = 0.10 kg", "g = 9.8 m/s²", "Height = 1.5 m"], "energy = 0.10 × 9.8 × 1.5 = 1.47 J", "The capsule begins with about 1.47 joules of gravitational potential energy.", "Crumple parts and motion must absorb or redirect that energy.", "Air drag and rotation are ignored."),
    test: test("Begin with a 0.5-metre drop onto a flat towel.", "The payload remains intact through three supervised 1.5-metre drops.", "Payload damage, crush distance, landing orientation, and final offset.", "crush-zone depth", "payload, frame, release orientation, height, landing surface, and inspector", ["2 cm crush zone", "4 cm crush zone", "6 cm crush zone"]),
    failures: ["The payload hits the frame|Suspension clearance is too small|Push the cup gently in each direction|Shorten bands or enlarge the frame", "The frame twists|Diagonal bracing is missing|Hold two corners and apply light twist|Add cross braces", "It lands outside the zone|Release adds sideways velocity|Film the hand and first 20 cm|Use a level release gate", "Damage repeats on one side|Mass is off-center or crush zones differ|Balance the capsule on a finger|Recenter payload and match zones"],
    tuning: "Increase stopping distance while keeping the payload centered. More padding adds mass, so use purposeful crush geometry instead of filling every space.",
    extensions: ["Easier|Plastic payload only|Test the structure without any food.", "Performance|Material budget|Protect the same payload using fewer straws.", "Advanced|Acceleration estimate|Use high-frame-rate video to estimate stopping time and average deceleration."],
    related: ["indoor-parachute-drop-test", "load-bearing-tower", "classroom-rescue-device"],
    builderMoment: "The capsule survived. The paper cone would like its deformation described as heroic."
  },
  {
    number: 82,
    title: "Indoor Parachute Drop Test",
    slug: "indoor-parachute-drop-test",
    difficulty: "Beginner",
    ageRange: "10-16",
    estimatedTime: "35-55 min",
    timeMinutes: 55,
    maxCost: 5,
    description: "Compare parachute canopy area while lowering the same lightweight payload through a safe indoor drop.",
    hook: "A larger canopy can push against more air, but only if it opens symmetrically. String length, holes, and payload balance decide whether drag slows the fall or creates a tangled spin.",
    outcome: "The parachute opens consistently and lowers a 20-gram payload through a 2-metre supervised drop at least 25 percent slower than the no-canopy control.",
    concepts: ["Air drag", "Terminal speed", "Experimental controls"],
    input: "release of a raised payload",
    output: "slower vertical descent",
    motion: "gravitational fall opposed by aerodynamic drag",
    losses: ["canopy leakage", "string tangles", "payload swing", "release variation"],
    principleName: "Drag-area tradeoff",
    principle: "A wider open canopy intercepts more moving air and creates more drag. The payload slows until weight and drag approach balance, though a short indoor drop may end before true terminal speed.",
    observe: "Watch the first half metre and note whether each canopy opens before timing most of the fall.",
    materials: householdMaterials("3|light plastic or tissue squares with 20, 30, and 40 cm sides|Create canopy sizes", "12|equal strings about 35 cm|Suspend the payload", "1|paper cup plus washers totaling 20 g|Provide a constant payload", "1|tape measure|Set drop height", "1|towel and taped landing zone|Provide a soft target", "1|stopwatch or slow-motion camera|Measure descent time"),
    alternative: "Use paper napkins with reinforced tape corners and a large paper clip payload.",
    hazard: "Perform supervised drops indoors at or below 2 metres, stand on the floor, and use an adult-held release pole rather than climbing furniture.",
    accessNote: "Use a pole-mounted clothespin release and assign timing and observation roles that do not require overhead reaching.",
    steps: ["Prepare equal payloads|Build one 20-gram cup and mark four equally spaced tie points.|Use the same payload for every canopy.", "Cut three canopies|Make 20, 30, and 40 cm squares from the same material.|Reinforce each corner with equal tape patches.", "Attach equal strings|Tie four 35 cm lines to each canopy and join them evenly to the cup.|Check that no line crosses another.", "Set the safe drop|Mark a 2-metre release height on a pole and place a towel below.|Clear a one-metre radius.", "Run the control|Drop the payload without a canopy three times.|Time from release to first towel contact.", "Test each canopy|Release each size three times in the same orientation.|Redo any trial with an obvious string snag and record why.", "Calculate averages|Find the average descent time for control and each size.|Record opening behavior separately.", "Inspect and explain|Compare canopy area, average time, and swing.|Identify the best stable design rather than only the slowest single trial."],
    math: math("Calculate canopy area", "area = side × side", ["Square side = 0.40 m", "The two perpendicular sides are equal"], "area = 0.40 × 0.40 = 0.16 m²", "The largest square has 0.16 square metres of projected area when fully open.", "More area can create more drag.", "Wrinkles and tilt reduce the effective area."),
    test: test("Drop the payload alone three times as a control.", "The parachute average is at least 25 percent slower than the control and opens in all three trials.", "Descent time, opening distance, swing, and landing offset.", "canopy side length", "payload, string length, material, drop height, release, and room", ["20 cm canopy", "30 cm canopy", "40 cm canopy"]),
    failures: ["The canopy never opens|Strings are tangled or release is folded|Hold by canopy center and inspect lines|Separate lines and use a consistent open release", "The payload spins|String lengths differ|Hang it motionless before dropping|Retie equal lengths", "Times are nearly identical|Drop is too short or canopy collapses|Film the opening phase|Use the full safe height and lighter canopy", "It drifts far sideways|Canopy is asymmetric or room air moves|Rotate and repeat with fans off|Square the canopy and balance ties"],
    tuning: "A stable open canopy is more useful than the largest wrinkled one. Larger area increases drag but also increases sensitivity to uneven strings and indoor air currents.",
    extensions: ["Easier|Two-size study|Compare control with one 30 cm canopy.", "Performance|Lowest landing speed|Use video frames to estimate speed over the final 0.5 metre.", "Creative|Canopy geometry|Compare equal-area circle and square shapes."],
    related: ["paper-helicopter-flight-test", "egg-drop-capsule", "wind-powered-sail-car"],
    builderMoment: "The parachute opened beautifully after landing, which was technically outside the test window."
  },
  {
    number: 83,
    title: "Paper Helicopter Flight Test",
    slug: "paper-helicopter-flight-test",
    difficulty: "Beginner",
    ageRange: "10-16",
    estimatedTime: "30-50 min",
    timeMinutes: 50,
    maxCost: 2,
    description: "Fold paper rotors that autorotate during a safe indoor drop and test how blade length changes descent time.",
    hook: "The falling body drives air across angled paper blades, and the resulting forces spin the rotor. Rotation increases drag and creates a stable, observable descent.",
    outcome: "The paper helicopter autorotates for most of a 2-metre drop and produces repeatable descent times within 15 percent across five trials.",
    concepts: ["Autorotation", "Drag", "Variables and controls"],
    input: "gravitational descent through still air",
    output: "rotor spin and slowed falling motion",
    motion: "vertical fall-to-rotary autorotation",
    losses: ["blade flutter", "body wobble", "paper deformation", "release spin"],
    principleName: "Autorotation",
    principle: "Air moving upward relative to the falling rotor pushes on the angled blades. Opposite blade forces create a torque that spins the paper and increases drag.",
    observe: "Draw one dark blade tip and count visible rotations in slow-motion video.",
    materials: householdMaterials("3|paper strips 5 × 20 cm|Create three rotor designs", "3|paper clips of equal mass|Weight the bodies", "1|ruler and pencil|Mark equal templates", "1|scissors|Cut blades", "1|adult-held release pole|Set safe height", "1|towel|Mark landing zone"),
    alternative: "Use index-card strips for stiffer blades and compare them separately from paper.",
    hazard: "Use only an indoor 2-metre release from a pole while everyone remains on the floor and the landing area is clear.",
    accessNote: "Provide pre-marked templates, a spring clothespin release, and bold contrasting blade-tip marks.",
    steps: ["Draw the template|Mark a 5 × 20 cm strip with a 7 cm body and two equal blade halves above.|Add a center cut line between blades.", "Cut the rotor|Cut the outline and center slit without narrowing the body.|Keep blade roots un-torn.", "Fold opposite blades|Fold one blade forward and one backward along the same line.|Crease gently so areas stay equal.", "Weight the body|Fold the lower strip upward twice and attach one paper clip.|Center the clip on the body.", "Set a control design|Make two copies with different blade lengths but equal total strip size.|Label them A, B, and C.", "Prepare the release|Mark 2 metres on an adult-held pole and place a towel below.|Turn off nearby fans.", "Run five drops each|Release without adding spin and time to first contact.|Alternate designs to reduce practice bias.", "Compare and inspect|Average times and note rotation direction, wobble, and blade damage.|Replace any creased trial piece."],
    math: math("Find average descent time", "average = sum of times / number of trials", ["Times = 1.8, 1.9, 1.7, 1.8, 1.8 s", "Trial count = 5"], "average = 9.0 / 5 = 1.8 s", "The mean descent time is 1.8 seconds.", "Averages reduce the effect of small timing differences.", "Hand timing and exact release height remain uncertain."),
    test: test("Drop one rotor from 1 metre to confirm stable rotation.", "It autorotates during most of five 2-metre drops with less than 15 percent timing spread.", "Descent time, rotations, wobble, and landing offset.", "blade length", "paper, body mass, drop height, release, room air, and timer", ["5 cm blades", "7 cm blades", "9 cm blades"]),
    failures: ["It falls without spinning|Blades face the same direction or are too flat|View from the side|Refold one blade opposite the other", "It tumbles|Paper clip is off-center or blades differ|Hang by the centerline|Center mass and trim evenly", "Rotation changes between runs|Release adds twist|Film the hand or clip|Use a fixed clothespin release", "Blades curl after drops|Paper is too soft or landing is hard|Compare before and after profiles|Use a towel and replace damaged rotors"],
    tuning: "Longer blades usually increase drag but may flutter. Keep mass, material, and release fixed so blade geometry is the only changed variable.",
    extensions: ["Easier|One reliable rotor|Build and test a single template.", "Performance|Rotation counter|Use slow motion to estimate turns per second.", "Advanced|Scale study|Double all dimensions, adjust mass, and predict the descent change."],
    related: ["indoor-parachute-drop-test", "cardboard-wind-turbine", "hand-crank-cardboard-desk-fan"],
    builderMoment: "The rotor did not fall. It descended with a carefully managed schedule."
  },
  {
    number: 84,
    title: "Wind-Powered Sail Car",
    slug: "wind-powered-sail-car",
    difficulty: "Beginner",
    ageRange: "10-16",
    estimatedTime: "40-65 min",
    timeMinutes: 65,
    maxCost: 7,
    description: "Capture airflow with an adjustable paper sail and tune a lightweight rolling chassis for speed and straight travel.",
    hook: "The fan never touches the car, but moving air pushes on its sail. Sail area, angle, and rolling friction turn that pressure into a measurable vehicle run.",
    outcome: "The car travels 2 metres from a fixed low-speed fan position, stays within a 50 cm lane, and completes three timed runs.",
    concepts: ["Aerodynamic force", "Rolling friction", "Center of pressure"],
    input: "moving air from a fixed household fan",
    output: "forward rolling motion",
    motion: "airflow-to-linear vehicle travel",
    losses: ["axle friction", "wheel slip", "sail leakage", "side force"],
    principleName: "Sail force",
    principle: "Air changes momentum as it meets the sail and applies a force to the car. A centered sail sends more of that force forward instead of turning the chassis.",
    observe: "Tilt the sail ten degrees and compare forward speed with sideways drift.",
    materials: householdMaterials("1|10 × 22 cm light-card chassis|Support axles and mast", "2|drinking-straw bearings|Guide axles", "2|straight covered skewers|Serve as axles", "4|equal bottle-cap or card wheels|Roll on the floor", "1|25 cm paper or straw mast|Hold the sail", "3|paper sails of measured area|Capture airflow", "1|guarded household fan on low speed|Provide consistent wind"),
    alternative: "Use a large sheet of cardboard to create a hand-powered air pulse instead of an electric fan.",
    hazard: "Use only a guarded fan with adult supervision, keep fingers and loose materials away from blades, and never modify the fan.",
    accessNote: "Use large clip-on sails and a release block so builders can change angle without fine knots.",
    steps: ["Build the chassis|Mark two square axle lines and reinforce the mast area.|Keep the base light and flat.", "Install bearings|Tape straws along the axle lines with equal overhang.|Sight through both to confirm parallel alignment.", "Add wheels|Center wheels on covered axles and leave side clearance.|Roll by hand through the test lane.", "Mount the mast|Brace a vertical mast at the chassis centerline with triangular gussets.|Push gently from each side to test stiffness.", "Make three sails|Cut equal-shape sails with areas of about 100, 200, and 300 cm².|Add reinforced clips at top and bottom.", "Set the wind course|Place the guarded fan 1 metre behind the start line on low speed.|Tape a 2-metre lane and keep its position fixed.", "Run baseline trials|Attach the medium sail square to the airflow and release from a block.|Measure time and drift for three runs.", "Compare sail variables|Test sail area or angle one at a time.|Keep fan, car mass, lane, and release unchanged."],
    math: math("Calculate average speed", "speed = distance / time", ["Distance = 2.0 m", "Time = 4.0 s"], "speed = 2.0 / 4.0 = 0.50 m/s", "The car averages half a metre per second.", "A larger sail may increase force but also side drift and mast bending.", "Fan airflow is not perfectly uniform."),
    test: test("Roll the car by hand through the lane before turning on the fan.", "The car completes 2 metres and stays within the marked lane in three trials.", "Travel time, drift, and mast angle.", "sail area", "car, fan setting, fan distance, floor, lane, and release", ["100 cm²", "200 cm²", "300 cm²"]),
    failures: ["The car veers|Sail or axles are not centered|Test rolling with the fan off|Square axles and center the sail", "It barely moves|Rolling friction is high or sail too small|Spin each axle and feel airflow|Realign bearings and increase area", "The mast bends|Sail force exceeds brace stiffness|Watch the mast during start|Add triangular gussets or reduce sail", "Wheels slip sideways|Side force is high|View from above|Turn the sail square to airflow"],
    tuning: "Low rolling resistance and straight alignment come first. More sail captures more air but can bend the mast and shift the center of pressure sideways.",
    extensions: ["Easier|One-sail course|Tune only axle alignment.", "Performance|Angle study|Compare 0, 10, and 20 degree sail angles.", "Creative|Cargo delivery|Carry equal washers and score speed plus payload."],
    related: ["balloon-powered-car", "cardboard-wind-turbine", "rubber-band-paddle-boat"],
    builderMoment: "The sail caught the wind. The left front wheel caught a completely different idea."
  },
  {
    number: 85,
    title: "Water-Hydraulic Lift",
    slug: "water-hydraulic-lift",
    difficulty: "Intermediate",
    ageRange: "11-17",
    estimatedTime: "60-90 min",
    timeMinutes: 90,
    maxCost: 12,
    description: "Connect water-filled syringes to raise a guided platform and compare input travel, output travel, and force.",
    hook: "Push one sealed plunger and pressure travels through the water to another. Different syringe sizes trade travel for force, while trapped air makes the system feel springy.",
    outcome: "The lift raises a 100-gram platform at least 5 cm, holds it for ten seconds, and completes five cycles without visible leakage.",
    concepts: ["Pascal's principle", "Hydraulic force", "Mechanical advantage"],
    input: "hand force and travel at the control syringe",
    output: "upward force and travel at the lift syringe",
    motion: "linear fluid displacement-to-linear lift motion",
    losses: ["trapped air", "seal friction", "hose expansion", "platform rubbing"],
    principleName: "Hydraulic pressure transmission",
    principle: "Pressure applied to a confined liquid acts throughout the system. A larger output piston can create greater force but moves a shorter distance for the same displaced fluid volume.",
    observe: "Press slowly and watch whether the output starts immediately; delayed motion often reveals trapped air or frame flex.",
    materials: householdMaterials("2|needle-free plastic syringes, one 10 mL and one 20 mL|Create input and output pistons", "1|60 cm flexible tubing that fits tightly|Carry water", "100 mL|water with one drop of food color|Transmit pressure visibly", "1|15 × 15 cm cardboard platform|Hold the test mass", "2|30 cm vertical cardboard rails|Guide platform travel", "100 g|bagged washers|Provide a safe test load", "1|shallow spill tray|Contain water"),
    extraTools: ["Towels", "Binder clips"],
    alternative: "Use two equal needle-free syringes for a one-to-one displacement demonstration.",
    hazard: "Use only needle-free syringes and clean water, work over a tray, keep water away from electronics, and never aim a disconnected tube at a face.",
    accessNote: "Add a wide plunger pad, large measurement marks, and a partner role for holding the frame while another operates the syringe.",
    steps: ["Build the guide frame|Mount two straight vertical rails on a wide base inside the spill tray.|Brace them so they stay parallel.", "Make the lift platform|Attach sleeves that slide along both rails without tilting.|Place the output syringe beneath the center.", "Fill the circuit|Draw colored water into both syringes and tubing until no large bubble remains.|Tap and purge air with tips upward.", "Connect securely|Push tubing fully onto both syringe tips and add cable ties or tape strain relief.|Keep plungers near mid-travel.", "Mount the output|Fix the larger syringe body vertically while its plunger supports the platform.|Align force through the platform center.", "Check an empty cycle|Press the input slowly and guide the platform through one full stroke.|Stop if tubing swells or leaks.", "Add the test load|Center 100 grams in a bag and raise it 5 cm at low speed.|Hold the input still for ten seconds.", "Compare syringe roles|Record input and output travel, then swap syringe sizes after draining safely.|Refill, purge, and repeat."],
    math: math("Estimate ideal force ratio", "force ratio = output piston area / input piston area", ["Input area = 1.0 cm²", "Output area = 2.0 cm²"], "force ratio = 2.0 / 1.0 = 2", "The ideal output force is twice the input force.", "Output travel is approximately half the input travel for equal displaced volume.", "Seal friction, hose expansion, and air reduce real performance."),
    test: test("Cycle the empty platform once over the spill tray.", "The system raises 100 grams by 5 cm, holds ten seconds, and shows no visible leak in five cycles.", "Input travel, output travel, supported mass, and pressure drift.", "input and output syringe size", "water fill, tubing, frame, load, speed, and starting plunger positions", ["equal syringes", "small input and large output", "large input and small output"]),
    failures: ["The lift feels springy|Air remains in the circuit|Hold tubing upright and compress gently|Purge bubbles and reconnect", "The platform tilts|Output is off-center or guides bind|Lift empty and watch both sleeves|Recenter the syringe and realign rails", "It sinks while held|A seal or connection leaks|Mark plunger position and inspect droplets|Tighten joints or replace the syringe", "The input will not move|A plunger is at its stop or tubing is pinched|Disconnect over the tray and inspect|Reset mid-stroke and open the hose path"],
    tuning: "Remove air and align the platform before increasing load. A larger output piston raises more force ideally, but it gives up travel and may need more input stroke.",
    extensions: ["Easier|Equal-syringe demo|Lift an empty platform and compare travel.", "Performance|Load curve|Add mass in 25-gram steps and record maximum height.", "Advanced|Pressure estimate|Calculate load force divided by output piston area and compare configurations."],
    related: ["water-hydraulic-cardboard-robot-arm", "mechanical-advantage-lift-challenge", "pulley-elevator"],
    builderMoment: "The hydraulic line had one tiny bubble and a very large opinion about precision."
  }
] satisfies GuideBlueprint[];

export const householdGuides = createGuides("Household engineering", blueprints);
