import { createGuides, type GuideBlueprint } from "../blueprintFactory";
import type { MathBite, TestPlan } from "../types";

const math = (title: string, formula: string, variables: string[], substitution: string, result: string, interpretation: string, assumptions: string): MathBite => ({ title, formula, variables, substitution, result, interpretation, assumptions });
const test = (firstTest: string, success: string, measure: string, variable: string, controls: string, trials: string[]): TestPlan => ({ firstTest, success, measure, variable, controls, trials });
function challengeMaterials(...items: [string, string, string, string, string, ...string[]]): GuideBlueprint["materials"] { return items; }

const blueprints = [
  {
    number: 86,
    title: "Pulley Elevator",
    slug: "pulley-elevator",
    difficulty: "Beginner",
    ageRange: "10-16",
    estimatedTime: "45-70 min",
    timeMinutes: 70,
    maxCost: 8,
    description: "Raise a small platform with fixed and movable pulleys, then compare input force, rope travel, and mechanical advantage.",
    hook: "A pulley can redirect a pull or divide a load among several rope segments. The elevator makes that tradeoff visible: less force requires more rope travel.",
    outcome: "The guided platform raises 30 cm with a 200-gram load, remains level, and completes five lifts without the line leaving a pulley.",
    concepts: ["Mechanical advantage", "Tension", "Work"],
    featured: true,
    input: "downward pull on a free rope end",
    output: "upward platform travel",
    motion: "linear pull-to-opposite linear lift",
    losses: ["axle friction", "rope rubbing", "platform tilt", "frame flex"],
    principleName: "Pulley mechanical advantage",
    principle: "A movable pulley shares the load across supporting rope segments. Ideal input force falls as the number of supporting segments increases, while required rope travel increases by the same factor.",
    observe: "Mark the rope every 10 cm and compare hand travel with platform travel in each pulley arrangement.",
    materials: challengeMaterials("1|60 cm-tall cardboard or classroom-frame tower|Support the elevator", "1|15 × 15 cm platform with two guide sleeves|Carry the load", "2|safe grooved pulleys or thread spools on dowels|Redirect the line", "2 m|smooth cord|Transmit pulling force", "200 g|bagged washers|Provide a test load", "1|spring scale measuring 0-10 N|Measure input force"),
    alternative: "Use thread spools on pencils as pulleys and a labeled bag of coins as the load.",
    hazard: "Keep the load below 250 grams, test below shoulder height, secure every support, and keep fingers clear of moving line and pulley grooves.",
    accessNote: "Add a large rope handle, high-contrast travel marks, and a partner role for reading the spring scale.",
    steps: ["Brace the tower|Build a wide base and two parallel vertical guides.|Push lightly in each direction and reinforce movement.", "Make the platform|Add two loose sleeves that slide on the guides and a centered load cup.|Confirm it cannot rotate off the rails.", "Mount the fixed pulley|Support its axle on both sides at the tower top.|Align the groove directly above the platform center.", "Test direction change|Tie the line to the platform, route over the pulley, and pull down.|Lift the empty platform 10 cm slowly.", "Add the movable pulley|Attach a second pulley beneath the platform and anchor one line end at the top.|Route down, around, and back up to the pull side.", "Mark travel distances|Place tape marks every 10 cm on the input line and tower.|Reset platform and scale to zero.", "Lift the test load|Add 200 grams and raise it 30 cm with each setup.|Record peak force and rope travel.", "Compare configurations|Repeat three trials for fixed-only and movable-pulley systems.|Keep load, speed, height, and scale angle fixed."],
    math: math("Calculate ideal input force", "input force = load force / supporting rope segments", ["Load force = 2.0 N", "Supporting segments = 2"], "input force = 2.0 / 2 = 1.0 N", "The ideal two-segment system needs about 1 newton of input force.", "The hand must pull about twice the platform travel.", "Pulley and rope friction make measured force higher."),
    test: test("Raise the empty platform 10 cm before adding mass.", "The system raises 200 grams by 30 cm for five cycles without derailment.", "Peak input force, rope travel, platform travel, and tilt.", "number of supporting rope segments", "load, platform, tower, lift height, pull speed, and spring scale", ["fixed pulley only", "one movable pulley", "same movable setup after alignment tuning"]),
    failures: ["The rope leaves the groove|Pulley and load are misaligned|View the system from front and side|Recenter the axle and add guide flanges", "The platform tilts|Lift point is off-center or guides bind|Raise empty and compare sleeve motion|Center the line and loosen sleeves", "Measured force is high|Axles rub or rope bends sharply|Spin pulleys unloaded|Widen bearing gaps and smooth the route", "The tower leans|Base or top brace is weak|Pull lightly with no load|Add diagonal bracing and a wider base"],
    tuning: "Reduce rubbing before increasing load. More supporting line segments reduce ideal force, but every extra bend adds friction and requires more pull distance.",
    extensions: ["Easier|Direction-only lift|Use one fixed pulley and an empty platform.", "Performance|Efficiency test|Compare ideal and measured mechanical advantage.", "Advanced|Four-segment hoist|Build a second movable stage and predict rope travel."],
    related: ["block-and-tackle-hoist", "mechanical-advantage-lift-challenge", "bottle-cap-pulley-crane"],
    builderMoment: "The elevator rose smoothly after the rope stopped trying to explore the frame."
  },
  {
    number: 87,
    title: "Marble Run Challenge",
    slug: "marble-run-challenge",
    difficulty: "Beginner",
    ageRange: "10-16",
    estimatedTime: "45-75 min",
    timeMinutes: 75,
    maxCost: 6,
    description: "Build a contained marble route with drops, turns, and a target finish while managing speed and reliability.",
    hook: "A good run is not the steepest route. It gives the marble enough energy for every section without letting speed overpower walls and turns.",
    outcome: "The marble completes a route at least 1.5 metres long and reaches the catch cup on four of five releases.",
    concepts: ["Potential energy", "Rolling motion", "Reliability"],
    input: "release from a fixed starting height",
    output: "controlled marble arrival in a target cup",
    motion: "gravitational descent-to-guided rolling",
    losses: ["rolling friction", "joint impacts", "track flex", "wall contact"],
    principleName: "Energy management on a track",
    principle: "Height gives the marble gravitational potential energy. Track slope and turns decide where that energy becomes speed and where friction or impacts remove it.",
    observe: "Mark three checkpoints and note where the marble is fastest, slowest, or most likely to leave the track.",
    materials: challengeMaterials("6|paper tubes cut lengthwise|Form track sections", "1|60 × 90 cm cardboard backboard|Support the route", "1|marble at least 16 mm wide|Provide a rolling object", "1|paper cup with padded bottom|Catch the marble", "1 roll|masking tape|Join adjustable sections"),
    alternative: "Use folded cardstock channels and a large wooden ball when small marbles are unsuitable.",
    hazard: "Contain every edge, keep the run below shoulder height, and store marbles away from young children after testing.",
    accessNote: "Use a larger ball, 6 cm-wide tracks, tactile checkpoint labels, and team roles for release and observation.",
    steps: ["Set the constraints|Mark start, finish, 1.5-metre minimum path, and maximum 60 cm drop.|Place the catch cup first.", "Build the start gate|Make a card slider that releases without pushing.|Test it on one short straight track.", "Add the first slope|Tape a shallow channel and support its midpoint.|Roll once and watch for twisting.", "Build a broad turn|Overlap two channels and raise the outside wall.|Keep the joint smooth in the travel direction.", "Add a controlled drop|Limit vertical drop to 10 cm and build a receiving funnel.|Contain every side.", "Connect to the finish|Use the remaining height gradually and align the last track with the cup.|Pad the landing.", "Run five trials|Reset only the marble and release gate.|Record the first failure location.", "Tune the weakest point|Change one slope, wall, or joint and repeat five trials.|Keep the rest of the route fixed."],
    math: math("Find completion reliability", "reliability = successful runs / total runs × 100%", ["Successful runs = 4", "Total runs = 5"], "reliability = 4 / 5 × 100% = 80%", "The run is 80 percent reliable in this test.", "More trials give stronger evidence.", "A changed release or damaged track affects results."),
    test: test("Roll through each new section at low speed before connecting the full route.", "Four of five complete releases reach the catch cup.", "Completion, travel time, derailment point, and wall contacts.", "one track slope", "marble, route, start height, gate, supports, and catch cup", ["baseline slope", "2 cm lower", "2 cm higher"]),
    failures: ["The marble stops at a joint|An overlap faces the wrong way or rises|Roll slowly by hand|Tape the upstream section over the downstream section", "It flies off a turn|Speed is high or outside wall low|Watch from above|Flatten the entry and raise the wall", "The route changes between runs|Supports flex or tape lifts|Press gently at each support|Brace and retape", "The marble misses the cup|Final alignment is off|Run only the last section|Widen the funnel and center the outlet"],
    tuning: "Repair the earliest unreliable section first. Steeper slopes overcome friction but increase impact speed, so distribute height rather than spending it all at the start.",
    extensions: ["Easier|Three-section run|Use one slope, one turn, and a cup.", "Performance|Ten-run reliability|Reach nine successful runs out of ten.", "Creative|Sound checkpoints|Add safe paper tabs that make different sounds."],
    related: ["gravity-marble-timer", "slowest-marble-track", "cardboard-marble-elevator"],
    builderMoment: "The marble completed four runs and used the fifth to review the wall height."
  },
  {
    number: 88,
    title: "Longest Paper Cantilever",
    slug: "longest-paper-cantilever",
    difficulty: "Beginner",
    ageRange: "10-16",
    estimatedTime: "35-55 min",
    timeMinutes: 55,
    maxCost: 2,
    description: "Extend paper beyond a desk edge while supporting a fixed tip load, then tune folds and counterbalance.",
    hook: "A cantilever has support at only one end. Every extra centimetre increases the bending moment near the clamp, so shape and anchoring matter more than they first appear.",
    outcome: "The paper structure extends at least 40 cm beyond the desk and holds a 10-gram tip load for ten seconds without an extra floor support.",
    concepts: ["Cantilevers", "Bending moment", "Counterbalance"],
    input: "downward load at the free tip",
    output: "bending resistance at the anchored end",
    motion: "static load-to-controlled deflection",
    losses: ["paper creasing", "clamp slip", "torsional twist", "local buckling"],
    principleName: "Cantilever bending moment",
    principle: "The turning effect at the support equals load force times distance. Moving the same load farther from the desk increases the demand on the paper and clamp.",
    observe: "Sight along the structure and find whether failure begins as vertical sag, sideways twist, or clamp slip.",
    materials: challengeMaterials("3|sheets of printer paper|Provide structural material", "50 cm|masking tape|Join paper only", "2|binder clips|Clamp the anchored end", "10 g|bagged washers|Create a fixed tip load", "1|ruler|Measure overhang and deflection"),
    alternative: "Use identical newspaper rectangles and clothespins while keeping limits equal for all teams.",
    hazard: "Use a light bagged load, keep feet away from the drop zone, and protect the desk edge from clamps.",
    accessNote: "Pre-mark fold lines and offer measuring, folding, loading, and documenting roles.",
    steps: ["Set the rules|Limit each team to three sheets, 50 cm tape, and two clips.|Define overhang from desk edge to load point.", "Test a flat control|Clamp one flat sheet with 20 cm overhang and add the load.|Record deflection after ten seconds.", "Choose a section|Fold paper into a tube, channel, or triangular beam.|Keep the cross-section consistent.", "Join the length|Overlap sheets by 4 cm and tape along both faces.|Avoid a hinge-like single tape line.", "Reinforce the root|Add a sleeve or deeper section near the desk edge.|Leave the distant tip light.", "Attach the load point|Tape a small loop at the center of the free end.|Prevent the load from pulling sideways.", "Increase overhang|Move outward in 5 cm increments and hold ten seconds each.|Stop at visible permanent damage.", "Measure and explain|Record maximum passing length, root deflection, and failure mode.|Sketch the final cross-section."],
    math: math("Compare bending moment", "moment = force × distance", ["Load force = 0.10 N", "Distance = 0.40 m"], "moment = 0.10 × 0.40 = 0.040 N·m", "The support resists about 0.040 newton-metres ideally.", "Doubling distance doubles the moment from the same load.", "Paper weight and dynamic loading add extra demand."),
    test: test("Test a flat 20 cm overhang as a control.", "The final structure holds 10 grams at 40 cm for ten seconds.", "Maximum overhang, tip deflection, failure mode, and material use.", "cross-section shape", "paper count, tape length, clamps, load, hold time, and desk", ["flat", "channel", "tube or triangle"]),
    failures: ["The root creases|Section is shallow near the clamp|Inspect the first permanent fold|Deepen or sleeve the root", "The beam twists|Cross-section is open or load off-center|View from the end|Close the section and center the load", "It slides from the desk|Clamp contact is small|Mark the paper at the edge|Increase anchored length without adding clips", "A joint folds|Overlap is short or tape acts as a hinge|Bend gently at each joint|Increase overlap and tape opposite faces"],
    tuning: "Put depth and reinforcement near the support where moment is greatest, while keeping the distant end light. More anchored paper improves grip but reduces available overhang.",
    extensions: ["Easier|Thirty-centimetre target|Use the same load with no joints.", "Performance|Efficiency score|Divide passing overhang by paper mass.", "Advanced|Deflection graph|Plot tip sag against distance in 5 cm steps."],
    related: ["strongest-index-card-beam", "paper-bridge-challenge", "bridge-under-budget"],
    builderMoment: "The cantilever reached 45 centimetres and then remembered gravity had voting rights."
  },
  {
    number: 89,
    title: "Strongest Index-Card Beam",
    slug: "strongest-index-card-beam",
    difficulty: "Beginner",
    ageRange: "10-16",
    estimatedTime: "35-60 min",
    timeMinutes: 60,
    maxCost: 3,
    description: "Turn identical index cards into beams and compare how cross-section geometry changes load capacity.",
    hook: "The card material stays the same, but a flat strip, channel, tube, and accordion resist bending very differently. Geometry decides where the material sits relative to the neutral axis.",
    outcome: "One beam spans 20 cm and supports at least 500 grams at midspan for ten seconds with a documented failure mode.",
    concepts: ["Beam stiffness", "Buckling", "Cross-sections"],
    input: "downward midspan test load",
    output: "structural resistance across two supports",
    motion: "static load-to-beam deflection",
    losses: ["local buckling", "crease damage", "support slip", "off-center loading"],
    principleName: "Cross-section stiffness",
    principle: "A deeper beam places more material farther from the neutral axis, increasing bending stiffness. Thin walls can still buckle before the material reaches its full strength.",
    observe: "Mark the top and bottom surfaces and note whether failure starts in top compression, bottom tension, or a side-wall buckle.",
    materials: challengeMaterials("12|identical index cards|Build four beam types", "60 cm|masking tape|Join edges", "2|books spaced 20 cm apart|Support beams", "1|small loading cup|Center test mass", "1 kg|bagged washers in 100 g groups|Apply load safely"),
    alternative: "Cut identical rectangles from cereal boxes when index cards are unavailable.",
    hazard: "Keep test supports low, add mass gradually, and use a tray to catch falling bagged weights.",
    accessNote: "Provide folding jigs, bold cross-section diagrams, and team roles for loading, counting, and observing.",
    steps: ["Define four designs|Choose flat stack, channel, closed tube, and accordion.|Sketch the end view of each.", "Build the flat control|Stack three cards and use equal tape at each end.|Do not pre-crease the span.", "Build the channel|Fold 2 cm walls along two long edges of three joined cards.|Keep wall heights equal.", "Build the tube|Fold and tape a rectangular closed section using the same card count.|Align the seam along one side.", "Build the accordion|Make equal alternating folds across three connected cards.|Keep the top surface level enough for the cup.", "Set the test rig|Space books exactly 20 cm and mark midspan.|Place a catch tray beneath.", "Load each beam|Add 100-gram bags every five seconds until failure or 1 kg.|Record deflection at 500 grams.", "Compare failures|Photograph or sketch the first damaged location.|Rank strength and mass efficiency."],
    math: math("Compare load-to-mass efficiency", "efficiency = supported mass / beam mass", ["Supported mass = 800 g", "Beam mass = 15 g"], "efficiency = 800 / 15 = 53.3", "The beam supports about 53 times its own mass.", "This compares designs that use different tape amounts.", "Scale readings and failure thresholds are approximate."),
    test: test("Load the flat control first in 100-gram steps.", "At least one shaped beam supports 500 grams for ten seconds.", "Failure load, deflection at 500 grams, beam mass, and failure location.", "cross-section shape", "card count, span, tape allowance, loading cup, rate, and weights", ["flat", "channel", "closed tube", "accordion"]),
    failures: ["The load cup punches through|Contact area is too small|Inspect a local top dent|Use one identical load-spreader card", "One wall buckles early|Fold heights or loading are uneven|View the end section|Refold symmetrically and center load", "The beam slides|Support friction is inconsistent|Mark end positions|Add equal nonslip pads", "Tape fails before paper|Seams carry peel load|Watch the seam edge|Place the seam on a side and increase overlap"],
    tuning: "Increase section depth without creating unsupported walls. Closed sections resist twisting well, but a poorly placed seam can become the first failure.",
    extensions: ["Easier|Two-shape comparison|Test flat and channel only.", "Performance|One-kilogram target|Redesign the strongest section without more cards.", "Advanced|Deflection stiffness|Calculate load divided by measured deflection before failure."],
    related: ["paper-bridge-challenge", "longest-paper-cantilever", "bridge-under-budget"],
    builderMoment: "The index card supported 800 grams and now expects to be addressed as a structural member."
  },
  {
    number: 90,
    title: "Slowest Marble Track",
    slug: "slowest-marble-track",
    difficulty: "Intermediate",
    ageRange: "10-17",
    estimatedTime: "55-85 min",
    timeMinutes: 85,
    maxCost: 6,
    description: "Design the slowest reliable marble descent using a fixed height, path length, and material budget.",
    hook: "Slowing a marble without stopping it is a control problem. Shallow slopes, long curves, and rolling resistance must remove speed consistently without introducing jams.",
    outcome: "The marble completes a 1.5-metre route from a 40 cm drop in at least 10 seconds on four of five runs.",
    concepts: ["Energy dissipation", "Slope", "Optimization"],
    input: "release from a fixed 40 cm height",
    output: "a delayed but complete marble arrival",
    motion: "gravitational descent-to-slow rolling motion",
    losses: ["rolling friction", "wall rubbing", "gentle impacts", "track deformation"],
    principleName: "Controlled energy dissipation",
    principle: "The marble must lose gravitational energy gradually through rolling friction and redirection. Abrupt obstacles can slow it, but they also increase random stops and rebounds.",
    observe: "Record split times for thirds of the track and locate where most delay occurs.",
    materials: challengeMaterials("6|paper channels totaling 1.5 m|Create the track", "1|marble at least 16 mm wide|Provide the moving mass", "1|40 cm-tall support board|Set the height limit", "1 roll|masking tape|Join and tune sections", "1|catch cup|Contain the finish", "1|stopwatch|Measure travel"),
    alternative: "Use folded paper strips and a large wooden ball when small marbles are not appropriate.",
    hazard: "Contain every side, keep the route below shoulder height, and collect small balls immediately after testing.",
    accessNote: "Use an oversized track, tactile split markers, and roles for release, timing, spotting, and recording.",
    steps: ["Set fixed limits|Mark a 40 cm start height and measure 1.5 m of track material.|Place the finish cup.", "Build the release gate|Use a sliding card that starts the marble without a push.|Practice three identical releases.", "Create a baseline slope|Connect the full path in one steady descent.|Time three runs before adding delays.", "Add broad turns|Replace straight sections with supported switchbacks.|Keep every section slightly downhill.", "Tune a friction zone|Add one removable strip of paper, felt, or tape texture.|Avoid anything that can trap the marble.", "Mark split points|Divide the path into equal thirds and label them.|Assign one timer or use video.", "Run five scored trials|Record total and split times plus any stop.|A stopped run does not qualify.", "Optimize one variable|Change one slope or friction zone and repeat.|Keep height, length, marble, and gate fixed."],
    math: math("Calculate average speed", "average speed = path length / time", ["Path length = 1.5 m", "Time = 12 s"], "speed = 1.5 / 12 = 0.125 m/s", "The marble averages 0.125 metres per second along the track.", "Local speed changes from section to section.", "Path length and hand timing are approximate."),
    test: test("Time three runs on a steady-slope baseline.", "Four of five scored runs finish in at least 10 seconds without stopping.", "Total time, split times, stops, and wall contacts.", "one track slope or friction strip", "height, path length, marble, release, catch, and room", ["baseline", "lower middle slope", "added removable friction strip"]),
    failures: ["The marble stops|A section is level or friction too high|Nudge it and mark the exact point|Increase local drop or reduce roughness", "It becomes fast near the end|Too much height remains late|Compare split times|Flatten the final third and spend height earlier", "Times vary|Release or track flex changes|Film the gate and supports|Stiffen the route and standardize release", "It falls out on turns|Entry speed is high or walls low|Watch from above|Widen, bank, and raise the outside edge"],
    tuning: "Aim for slow motion in every section, not one dramatic delay. Increasing friction can lengthen time, but the reliability penalty grows quickly near the point of stopping.",
    extensions: ["Easier|Eight-second target|Use a 1-metre route.", "Performance|Fifteen-second target|Reach four of five reliable runs.", "Advanced|Section model|Predict total time by summing average split times."],
    related: ["gravity-marble-timer", "marble-run-challenge", "friction-investigation-sled"],
    builderMoment: "The marble took twelve seconds to finish and spent nine of them considering one seam."
  },
  {
    number: 91,
    title: "Cup-Stacking Mechanical Hand",
    slug: "cup-stacking-mechanical-hand",
    difficulty: "Intermediate",
    ageRange: "10-17",
    estimatedTime: "60-90 min",
    timeMinutes: 90,
    maxCost: 8,
    description: "Build a string-driven cardboard hand that grips paper cups and complete a timed stacking task.",
    hook: "Pulling tendons curl the fingers, while elastic bands reopen them. The challenge combines linkage geometry, grip force, and coordinated control.",
    outcome: "The hand picks up, moves, and stacks three paper cups in under 90 seconds without direct contact from the operator's fingers.",
    concepts: ["Tendons", "Flexure joints", "Grip force"],
    input: "hand pulls on five control strings",
    output: "finger curling and cup grip",
    motion: "linear tendon pull-to-curved finger motion",
    losses: ["string friction", "joint stiffness", "uneven tension", "cardboard bending"],
    principleName: "Tendon-driven motion",
    principle: "A string routed along the inside of a segmented finger shortens that side when pulled, causing the flexible joints to curl around the cup.",
    observe: "Pull one tendon slowly and identify which joint moves first and where string rubs against cardboard.",
    materials: challengeMaterials("1|20 × 30 cm corrugated-cardboard palm|Support fingers", "5|3 × 20 cm card finger strips|Create segmented fingers", "2 m|smooth string|Act as tendons", "5|small elastic bands|Return fingers open", "3|paper cups|Provide stacking targets", "1|wide wrist strap|Secure the device"),
    alternative: "Use drinking-straw finger segments threaded on string for an easier large-scale hand.",
    hazard: "Use lightweight paper cups only, keep strings away from necks, and let an adult make narrow slots or holes.",
    accessNote: "Combine finger strings into one large handle or assign two operators to pull grouped tendons.",
    steps: ["Trace the palm|Cut a broad palm and mark five finger roots with thumb opposite the fingers.|Round every edge.", "Segment the fingers|Score three fold joints on each strip without cutting through.|Tape the back of each joint as a hinge.", "Attach fingers|Tape each root to the palm and check the open shape.|Angle the thumb toward the center grip zone.", "Route the tendons|Thread string from each fingertip through guides on the palm side.|Leave independent pull loops at the wrist.", "Add return bands|Connect light elastic across the back of each joint.|Use only enough tension to reopen the finger.", "Fit the wrist support|Attach a broad strap and reinforce the tendon exit edge.|Confirm no string crosses skin.", "Practice one-cup grip|Approach an upright cup, pull evenly, lift 10 cm, and release.|Adjust thumb position before adding speed.", "Run the stack challenge|Move three cups into a pyramid and time three attempts.|Record drops, crushed cups, and completion time."],
    math: math("Calculate success rate", "success rate = completed stacks / attempts × 100%", ["Completed stacks = 2", "Attempts = 3"], "success rate = 2 / 3 × 100% = 66.7%", "Two of three attempts succeeded.", "More practice or grip tuning may raise reliability.", "Three attempts are a small sample."),
    test: test("Lift one empty cup 10 cm before attempting a stack.", "The device stacks three cups in under 90 seconds without direct hand contact.", "Completion time, dropped cups, tendon pulls, and cup deformation.", "thumb angle", "hand body, strings, cups, operator, course, and starting arrangement", ["thumb straight", "thumb angled 20°", "thumb angled 35°"]),
    failures: ["The cup slips|Thumb opposition or tendon tension is low|Hold the cup without lifting|Angle the thumb and shorten slack", "Fingers stay closed|Return bands are weak or strings bind|Release handles one at a time|Open guides and replace bands", "One finger curls early|Tendon lengths differ|Mark strings at full-open position|Equalize pull loops", "The palm bends|Load path is not reinforced|Grip one cup and view the palm edge|Laminate the palm and add ribs"],
    tuning: "Reliable cup contact matters more than maximum squeeze. Stronger tendons can crush cups and overload joints, while too much return tension makes the controls hard to pull.",
    extensions: ["Easier|Two-finger gripper|Use a thumb and one wide finger.", "Performance|Six-cup stack|Optimize controls for a taller pyramid.", "Advanced|Single-handle control|Design a tendon comb that closes fingers in sequence."],
    related: ["cardboard-mechanical-hand", "parallel-jaw-gripper", "linkage-grabber-arm"],
    builderMoment: "The hand stacked two cups and then shook hands with the third."
  },
  {
    number: 92,
    title: "Load-Bearing Tower",
    slug: "load-bearing-tower",
    difficulty: "Intermediate",
    ageRange: "10-18",
    estimatedTime: "55-90 min",
    timeMinutes: 90,
    maxCost: 5,
    description: "Build the tallest paper-and-tape tower that supports a fixed top load and survives a gentle stability test.",
    hook: "Tall towers rarely fail because paper is crushed evenly. They buckle, twist, or tip when slender columns and weak joints let the load move away from the base.",
    outcome: "The tower reaches at least 60 cm, supports 500 grams for ten seconds, and remains standing after a gentle table tap.",
    concepts: ["Buckling", "Compression", "Stability"],
    input: "downward top load and small side disturbance",
    output: "stable compression paths to the base",
    motion: "static loading-to-small structural deflection",
    losses: ["column buckling", "joint slip", "base tipping", "frame twist"],
    principleName: "Braced compression structure",
    principle: "Columns carry the load downward, while diagonal braces prevent the frame from changing shape. A wide base keeps the combined center of mass inside the support area.",
    observe: "Watch the longest unbraced column and mark whether it bends sideways before any material crushes.",
    materials: challengeMaterials("20|sheets of printer paper|Form columns and braces", "1 m|masking tape|Join members", "1|15 × 15 cm load plate|Spread the top load", "500 g|bagged washers|Apply a safe test load", "1|metre stick|Measure tower height"),
    alternative: "Use newspaper sheets cut to equal mass and labeled bags of coins for load.",
    hazard: "Keep the tower on the floor during final loading, add mass from the side, and use bagged weights that cannot scatter.",
    accessNote: "Use rolling mandrels, pre-measured tape strips, and team roles for member production, assembly, loading, and observation.",
    steps: ["Set the constraints|Limit paper, tape, footprint, and 500-gram load.|Draw a 30 × 30 cm maximum base square.", "Choose a frame plan|Sketch three- or four-column geometry with brace levels every 20 cm.|Mark where the load plate sits.", "Roll equal columns|Roll paper tightly around a pencil and tape the seam.|Make matching diameters and lengths.", "Build the base level|Join columns with horizontal beams and diagonals.|Check both diagonals of the footprint for squareness.", "Add upper levels|Extend columns with overlapped sleeves and brace each new bay.|Stagger joints between sides.", "Install the load plate|Center a stiff plate across every top column.|Prevent it from sliding.", "Run staged loading|Add 100 grams every five seconds while watching columns.|Stop at sudden lean or permanent buckle.", "Perform the stability tap|After passing 500 grams, tap the table gently from a marked distance.|Record top movement and recovery."],
    math: math("Calculate slenderness", "slenderness ratio = unsupported length / member width", ["Unsupported length = 20 cm", "Tube width = 2 cm"], "ratio = 20 / 2 = 10", "This member has a slenderness ratio of 10.", "Shorter braced lengths are less prone to buckling.", "Paper tubes are not solid, uniform engineering columns."),
    test: test("Load the first 20 cm frame with 100 grams before building taller.", "The completed tower holds 500 grams for ten seconds and survives one gentle tap.", "Height, load, top sway, first buckle, and material use.", "vertical brace spacing", "paper, tape, footprint, load plate, loading rate, and floor", ["30 cm spacing", "20 cm spacing", "15 cm spacing"]),
    failures: ["One column bows|Unbraced length is too great|View each face during low load|Add a diagonal or mid-level tie", "The tower twists|Faces lack triangulation|Hold base and nudge top lightly|Add opposing diagonal braces", "The base tips|Footprint is narrow or load off-center|Project the load position downward|Widen base and center plate", "A splice crushes|Overlap is short or all joints align|Inspect the first collapsed seam|Use longer sleeves and stagger splices"],
    tuning: "Shorten unsupported column lengths before adding more paper to every member. Extra bracing increases stability but also adds mass and joint complexity.",
    extensions: ["Easier|Forty-centimetre target|Use the same load with fewer levels.", "Performance|Efficiency score|Multiply passing height by load and divide by tower mass.", "Advanced|Lateral test|Measure top displacement from equal gentle side pulls."],
    related: ["paper-tower-challenge", "center-of-mass-balancing-sculpture", "bridge-under-budget"],
    builderMoment: "The tower passed 500 grams and failed a highly opinionated piece of tape."
  },
  {
    number: 93,
    title: "Bridge Under Budget",
    slug: "bridge-under-budget",
    difficulty: "Intermediate",
    ageRange: "11-18",
    estimatedTime: "70-110 min",
    timeMinutes: 110,
    maxCost: 6,
    description: "Design a bridge under a points budget, purchase materials strategically, and optimize load capacity per unit cost.",
    hook: "Engineering is rarely about maximum strength with unlimited material. This challenge prices every beam, joint, and reinforcement so teams must decide where structure earns its cost.",
    outcome: "The bridge spans 40 cm, supports at least 1 kilogram for ten seconds, and stays within a 100-point material budget.",
    concepts: ["Design optimization", "Trusses", "Cost efficiency"],
    input: "downward center-span test load",
    output: "distributed force paths to two supports",
    motion: "static loading-to-structural deformation",
    losses: ["joint slip", "member buckling", "deck bending", "support movement"],
    principleName: "Strength-to-cost optimization",
    principle: "A truss carries load efficiently when members align with tension and compression paths. Budget scoring rewards material placed where force is greatest instead of uniform overbuilding.",
    observe: "Before loading, predict one tension member and one compression member, then watch how each deforms.",
    materials: challengeMaterials("60|craft sticks priced at 1 point each|Form structural members", "100 cm|masking tape priced at 1 point per 5 cm|Make joints", "1|10 × 40 cm card deck priced at 20 points|Carry the load", "2|supports spaced 40 cm|Define the span", "2 kg|bagged test mass in 250 g groups|Load safely", "1|small loading plate|Spread center load"),
    alternative: "Use rolled paper beams with a teacher-assigned points menu based on material mass.",
    hazard: "Test near floor level behind a clear line, add only bagged mass, and stop at visible rapid deformation.",
    accessNote: "Provide a large-print price menu, pre-counted material bundles, and roles for budget, structure, construction, and test documentation.",
    steps: ["Publish the price list|Write costs for sticks, tape, deck, and optional reinforcements.|Give every team 100 points.", "Sketch two concepts|Draw side and top views with predicted force paths.|Estimate the cost of each before choosing.", "Build identical side trusses|Lay members over one full-size template.|Make joints overlap rather than meet at unsupported points.", "Connect the sides|Add cross beams at panel points and diagonal top bracing.|Keep the span square.", "Install the deck|Attach the light deck at multiple panel points.|Avoid relying on one tape loop.", "Audit the budget|Count every member and measured tape length.|Remove or document any over-budget material.", "Run staged loading|Add 250 grams every ten seconds at midspan.|Record deflection and first damage.", "Calculate the score|Use maximum passing load divided by points spent.|Compare which material choices produced value."],
    math: math("Calculate budget efficiency", "efficiency = passing load / points spent", ["Passing load = 1500 g", "Cost = 90 points"], "efficiency = 1500 / 90 = 16.7 g/point", "The bridge supports about 16.7 grams per budget point.", "A cheaper bridge can outperform a stronger expensive bridge on this score.", "Load increments and material pricing are classroom conventions."),
    test: test("Press lightly on the empty deck and inspect every joint before adding mass.", "The bridge spans 40 cm, stays within 100 points, and holds 1 kilogram for ten seconds.", "Passing load, cost, midspan deflection, and first failure.", "one reinforcement purchase", "span, load location, rate, material prices, supports, and score formula", ["baseline design", "added top chord", "same cost moved to diagonal bracing"]),
    failures: ["The deck folds|Load does not reach truss panel points|Watch deck before side members|Add cross beams under the load plate", "A top member bows|Compression member is too slender|View from the side during low load|Shorten with bracing or laminate it", "The bridge twists|Side trusses are not cross-braced|Push one top corner gently|Add diagonal connections between sides", "The budget is exceeded|Materials were not tracked during assembly|Compare build to purchase sheet|Remove low-value pieces or redesign"],
    tuning: "Move material toward observed failure locations rather than adding it everywhere. Stronger reinforcement may reduce budget efficiency if it does not increase the passing load step.",
    extensions: ["Easier|Five-hundred-gram target|Use a 30 cm span and 80 points.", "Performance|Auction pricing|Change material prices based on class demand.", "Advanced|Optimization round|Rebuild with 10 fewer points while matching the first load."],
    related: ["straw-truss-bridge", "paper-bridge-challenge", "strongest-index-card-beam"],
    builderMoment: "The bridge had twelve points left and immediately hired another diagonal."
  },
  {
    number: 94,
    title: "Tabletop Zipline Carrier",
    slug: "tabletop-zipline-carrier",
    difficulty: "Beginner",
    ageRange: "10-16",
    estimatedTime: "40-65 min",
    timeMinutes: 65,
    maxCost: 6,
    description: "Build a carrier that travels down a low tabletop line, delivers a payload, and stops inside a target zone.",
    hook: "Gravity pulls the carrier downhill, wheel or hook friction controls its speed, and a braking system decides where it stops. The challenge is reliable delivery, not maximum speed.",
    outcome: "The carrier moves a 50-gram payload along a 2-metre low line and stops inside a 30 cm target on four of five runs.",
    concepts: ["Gravity", "Friction", "Kinetic energy"],
    input: "release from the raised end of a sloped line",
    output: "payload travel and controlled stop",
    motion: "gravitational descent-to-linear carrier motion",
    losses: ["line friction", "carrier swing", "wheel rubbing", "brake deformation"],
    principleName: "Slope-driven transport",
    principle: "The height difference provides gravitational energy. Friction and a deformable brake remove that energy so the carrier can stop near a target instead of striking the support.",
    observe: "Mark the line every 50 cm and compare speed changes before and during braking.",
    materials: challengeMaterials("2 m|smooth cord|Create the zipline", "2|secure supports no higher than 1 m|Hold line ends", "1|thread spool or grooved wheel|Carry the vehicle", "1|light cardboard basket|Hold payload", "50 g|bagged washers|Provide cargo", "3|paper or sponge brake designs|Stop the carrier", "1|towel|Pad the line end"),
    alternative: "Use a large paper-clip hook sliding on string if a spool is unavailable, and keep the slope gentle.",
    hazard: "Keep the line below shoulder height, use lightweight cargo, pad both ends, and keep faces and hands out of the travel path.",
    accessNote: "Use a large release lever, bold distance markers, and separate roles for loading, releasing, timing, and catching.",
    steps: ["Set the low line|Secure two supports 2 metres apart with a 30 cm height difference.|Pull the cord taut but not enough to tip supports.", "Build the carrier|Suspend a small basket below a grooved wheel or broad hook.|Keep the payload beneath the line for stability.", "Add a release tab|Hold the carrier with a card gate instead of fingers.|Mark one exact start position.", "Pad the finish|Wrap the final support and place a towel beneath.|Mark a 30 cm stopping zone before it.", "Run empty trials|Release the carrier three times without cargo.|Watch swing and wheel alignment.", "Add the payload|Center 50 grams in a sealed bag and secure it in the basket.|Confirm the carrier hangs level.", "Build a brake|Add a paper brush, sponge contact, or line flag near the finish.|Start with light contact.", "Tune five runs|Change only brake length or position and record stopping point.|Score runs ending fully inside the zone."],
    math: math("Find height-based potential energy", "energy = mass × g × height drop", ["Mass = 0.08 kg", "g = 9.8 m/s²", "Drop = 0.30 m"], "energy = 0.08 × 9.8 × 0.30 = 0.235 J", "About 0.24 joules are available before friction.", "The brake must remove the remaining kinetic energy safely.", "Line sag and rolling friction reduce motion."),
    test: test("Release the empty carrier once while an adult guards the finish.", "With 50 grams, four of five runs stop inside the 30 cm target.", "Stopping position, travel time, swing angle, and brake contact.", "brake length", "line, slope, carrier, cargo, start, and finish padding", ["short brake", "medium brake", "long brake"]),
    failures: ["The carrier falls off|Wheel groove is shallow or line sags|Move it slowly by hand|Use a deeper guide and tension the line safely", "It swings badly|Payload is high or off-center|Hang motionless and release|Lower and center the cargo", "It stops too early|Brake contact is excessive|Mark the first contact point|Shorten or move the brake later", "It hits the support|Brake is weak or slope too steep|Run empty and guard the finish|Increase braking and reduce height difference"],
    tuning: "Stabilize the carrier before adjusting speed. More slope improves reliable starts but increases braking demand and impact risk.",
    extensions: ["Easier|Empty delivery|Stop the carrier with no cargo.", "Performance|Precision score|Measure absolute distance from target center.", "Creative|Release package|Design a mechanical drop-off inside the target."],
    related: ["classroom-rescue-device", "pulley-elevator", "friction-investigation-sled"],
    builderMoment: "The package arrived on time and parked three centimetres past its reservation."
  },
  {
    number: 95,
    title: "Classroom Rescue Device",
    slug: "classroom-rescue-device",
    difficulty: "Intermediate",
    ageRange: "10-18",
    estimatedTime: "65-100 min",
    timeMinutes: 100,
    maxCost: 8,
    description: "Design a remote tool that retrieves a model supply package from a taped hazard zone without crossing the boundary.",
    hook: "Rescue engineering turns a goal into constraints: reach, grip, control, payload safety, and operator distance. Teams must choose a mechanism that works from outside the zone.",
    outcome: "The device retrieves a 100-gram model supply bag from 1 metre away and places it in a target box within two minutes.",
    concepts: ["Design constraints", "Levers", "Remote manipulation"],
    input: "hand motion outside a marked boundary",
    output: "controlled pickup and placement of a payload",
    motion: "remote pull, push, or linkage motion-to-object transport",
    losses: ["tool flex", "grip slip", "joint backlash", "operator misalignment"],
    principleName: "Constraint-based mechanism design",
    principle: "A rescue tool must transmit hand motion across distance while supporting the payload. Long reach increases bending and reduces control, so stiffness and grip geometry must be balanced.",
    observe: "Watch the far end while a teammate moves the handle 5 cm; compare intended and actual tip motion.",
    materials: challengeMaterials("10|craft sticks or rolled-paper tubes|Form reach structure", "1 m|string|Operate a remote grip or hook", "6|rubber bands and binder clips|Create joints and returns", "100 g|sealed model supply bag|Provide rescue payload", "1|shoebox target|Receive the payload", "1 roll|masking tape|Mark a 1 m hazard zone"),
    alternative: "Use cardboard strips, drinking straws, and a paper-cup scoop rather than commercial gripper parts.",
    hazard: "Use only lightweight model payloads on the floor, keep the device below shoulder height, and prohibit swinging or throwing.",
    accessNote: "Offer hook, scoop, and gripper strategies plus roles for operator, spotter, designer, and recorder.",
    steps: ["Define the scenario|Tape a boundary 1 metre from the payload and place the target beside the operator.|Set a two-minute limit.", "Choose a pickup method|Sketch a hook, scoop, clamp, or loop and explain why it matches the bag.|Identify one likely failure.", "Build the reach beam|Join members with long overlaps and add depth using a triangular or box section.|Keep mass low at the far end.", "Create the end tool|Attach the chosen pickup geometry and test it by hand first.|Round all edges touching the bag.", "Add remote control|Route string or a linkage to the operator handle.|Provide a return spring when the tool must reopen.", "Run a no-load reach test|Move the tip through the full path without crossing the boundary.|Reinforce visible bending.", "Practice one retrieval|Pick up the bag, clear the zone, and lower it into the box.|Do not drag it across the boundary.", "Complete three scored runs|Record time, boundary contacts, drops, and successful delivery.|Change one feature between rounds."],
    math: math("Calculate payload moment", "moment = payload force × horizontal reach", ["Payload force = 1.0 N", "Reach = 1.0 m"], "moment = 1.0 × 1.0 = 1.0 N·m", "The handle and beam resist about one newton-metre from the payload alone.", "The device's own mass adds more bending moment.", "The payload may not stay exactly horizontal."),
    test: test("Operate the end tool by hand before attaching the long reach beam.", "The device retrieves 100 grams from 1 metre and places it in the target within two minutes.", "Time, drops, boundary touches, tip deflection, and grip success.", "end-tool geometry", "reach, payload, boundary, operator position, target, and time limit", ["hook", "scoop", "clamp or loop"]),
    failures: ["The beam bends too far|Section is shallow or tip is heavy|Hold the payload 5 cm above the floor|Deepen the beam and lighten the tool", "The bag slips|Contact shape or normal force is poor|Lift only 2 cm and pause|Widen contact or add nonslip paper", "Control reverses unexpectedly|String routing crosses or linkage flips|Move the handle slowly unloaded|Separate guides and add hard stops", "The target is missed|Tip motion is too sensitive|Move the handle 1 cm and measure tip travel|Shorten lever arm or add a larger handle"],
    tuning: "Stiffen the long beam without making the far end heavy. A firm grip prevents drops, but excessive force can make release into the target difficult.",
    extensions: ["Easier|Fifty-gram payload|Use a wide scoop from 60 cm away.", "Performance|Two-object rescue|Retrieve two shapes with one tool.", "Advanced|Operator feedback|Add a mechanical indicator that shows grip closure."],
    related: ["linkage-grabber-arm", "cup-stacking-mechanical-hand", "tabletop-zipline-carrier"],
    builderMoment: "The rescue succeeded. The gripper then refused to release the evidence."
  },
  {
    number: 96,
    title: "Rube Goldberg Switch",
    slug: "rube-goldberg-switch",
    difficulty: "Intermediate",
    ageRange: "10-18",
    estimatedTime: "60-95 min",
    timeMinutes: 95,
    maxCost: 8,
    description: "Create a five-stage chain reaction whose final motion presses a low-voltage switch reliably.",
    hook: "The final task is tiny: press one switch. The engineering lives in five carefully tuned handoffs that move energy through different mechanisms without skipping or stalling.",
    outcome: "One start action triggers five distinct stages and closes a battery-powered continuity switch on four of five runs.",
    concepts: ["Energy transfer", "Systems", "Reliability"],
    input: "one deliberate release at stage one",
    output: "momentary low-voltage switch closure",
    motion: "sequential falling, rolling, and lever motions-to-linear press",
    losses: ["handoff misalignment", "surface friction", "trigger flex", "reset variation"],
    principleName: "System interfaces",
    principle: "Each stage is a subsystem with an input and output. The whole machine works only when every output has enough travel, force, and accuracy to trigger the next input.",
    observe: "Label the five interfaces and record the first failed handoff instead of only marking the full run as failed.",
    materials: challengeMaterials("10|dominoes or card standups|Create a falling stage", "2|paper ramps and large balls|Create rolling stages", "2|rulers on pencil pivots|Create lever stages", "1|cardboard arcade button or battery continuity tester|Show final switch state", "1 roll|masking tape|Mark and secure positions"),
    alternative: "Use a paper flag as the final output when no low-voltage tester is available.",
    hazard: "Use only contained lightweight objects and a battery-powered tester; no mains electricity, projectiles, glass, or elevated drops.",
    accessNote: "Assign one team member per stage, use large start controls, and mark all reset positions in high contrast.",
    steps: ["Define the switch press|Measure the cap travel and force using a finger or spring scale.|Build the last lever to exceed both safely.", "Build backward one stage|Use a falling cup or rolling ball to move the final lever.|Test this pair five times.", "Add the middle lever|Make a broad target that receives the previous output.|Add stops so it cannot jump past the next trigger.", "Create a contained ramp|Guide a large ball between walls into the middle target.|Use a release gate rather than hand push.", "Add the first stage|Place dominoes or card standups that open the gate.|Mark spacing with a jig.", "Separate early triggers|Tap the table lightly and confirm later stages remain ready.|Widen bases where vibration causes early movement.", "Run interface trials|Test each adjacent pair five times and record misses.|Tune the lowest-performing connection.", "Run five full sequences|Reset from a numbered photo checklist.|Count switch closures and first failures."],
    math: math("Estimate full-system reliability", "system probability = p1 × p2 × p3 × p4 × p5", ["Each stage reliability p = 0.95", "Five stages"], "probability = 0.95⁵ = 0.774", "Five 95-percent stages produce about 77 percent ideal full-run reliability.", "Improving every handoff matters.", "Stage failures may not be independent in a real machine."),
    test: test("Test the final switch lever by hand before connecting earlier stages.", "Four of five complete runs close the switch from one start action.", "First failed stage, switch closure, run time, and reset errors.", "target size at the weakest interface", "five stages, objects, positions, start energy, table, and switch", ["baseline target", "2 cm wider", "4 cm wider"]),
    failures: ["The switch is not pressed fully|Final lever travel or force is low|Trigger the last stage alone|Move the pivot or increase safe falling mass slightly", "A stage fires early|Vibration reaches an unstable trigger|Tap near stage one|Widen bases and increase spacing", "The ball misses|Ramp exit and target do not align|Run only that interface|Add side guides and enlarge target", "Reset creates new failures|Positions are not documented|Compare with ready-state photo|Add numbered outlines and checklist"],
    tuning: "Improve the least reliable interface before adding spectacle. Larger targets and clean stops improve reliability, while sensitive triggers reduce needed energy but increase early firing.",
    extensions: ["Easier|Three-stage switch|Use dominoes, ramp, and lever.", "Performance|Nine-of-ten goal|Reach 90 percent full-run reliability.", "Creative|Dual output|Press the switch and raise a paper message."],
    related: ["chain-reaction-machine", "cardboard-arcade-button", "mechanical-counter"],
    builderMoment: "The machine moved for twelve seconds to accomplish what one finger considered a brief meeting."
  },
  {
    number: 97,
    title: "Mechanical Advantage Lift Challenge",
    slug: "mechanical-advantage-lift-challenge",
    difficulty: "Intermediate",
    ageRange: "11-18",
    estimatedTime: "60-95 min",
    timeMinutes: 95,
    maxCost: 10,
    description: "Choose a lever, pulley, wheel-and-axle, or combination system to lift the same load with the smallest measured input force.",
    hook: "Mechanical advantage is a trade: lower input force requires greater input distance. Teams must prove their advantage with force and travel measurements, not appearances.",
    outcome: "The device lifts 500 grams by 20 cm with measured input force below 3 newtons and no structural failure.",
    concepts: ["Mechanical advantage", "Work", "Efficiency"],
    input: "measured hand force over an input distance",
    output: "upward travel of a 500-gram load",
    motion: "linear or rotary input-to-linear lift",
    losses: ["bearing friction", "rope stretch", "frame flex", "misalignment"],
    principleName: "Force-distance tradeoff",
    principle: "Ideal machines conserve work: reducing input force requires a proportionally longer input distance. Real systems need extra work because friction and deformation waste energy.",
    observe: "Measure input and output distances during the same lift and compare their ratio with the force ratio.",
    materials: challengeMaterials("1|500 g bagged load|Provide a shared challenge mass", "1|spring scale measuring 0-10 N|Measure input force", "2 m|smooth cord|Transmit force", "2|pulleys or thread spools|Offer pulley options", "2|rulers and dowels|Offer lever or wheel-and-axle options", "1|braced tabletop frame|Support the system"),
    alternative: "Use a calibrated rubber-band force scale after comparing it with known masses.",
    hazard: "Keep the load below knee height, secure the frame, use bagged mass, and keep hands clear of pinch and drop zones.",
    accessNote: "Use large handles and split measurement, operating, spotting, and recording roles.",
    steps: ["Measure direct lift|Use the spring scale to raise 500 grams slowly by 20 cm.|Record peak and steady force as a baseline.", "Choose a machine|Sketch a lever, pulley, wheel-and-axle, or safe combination.|Predict force and input travel.", "Build the frame|Brace supports in the pull direction and add a wide base.|Test with no load.", "Install the mechanism|Align ropes, pivots, or axles with the load center.|Add hard stops where motion could overtravel.", "Mark distances|Place scale marks on input path and load path.|Zero the spring scale in the pulling direction.", "Run a 100-gram test|Lift slowly and inspect all supports.|Repair rubbing or flex before full load.", "Lift the challenge load|Raise 500 grams by 20 cm in three trials.|Record input force and distance.", "Calculate performance|Find actual mechanical advantage and efficiency.|Explain the force-distance tradeoff."],
    math: math("Calculate actual mechanical advantage", "AMA = output force / input force", ["Output force = 4.9 N", "Input force = 2.5 N"], "AMA = 4.9 / 2.5 = 1.96", "The measured mechanical advantage is about 2.", "Input distance should be roughly twice output distance in an ideal system.", "Friction makes actual efficiency lower than 100 percent."),
    test: test("Lift 100 grams through the full travel before using 500 grams.", "The system raises 500 grams by 20 cm with input force below 3 newtons.", "Input force, input distance, output distance, and frame deflection.", "machine configuration", "load, lift height, scale, operator speed, frame, and test method", ["direct lift", "single movable pulley or lever", "tuned combination"]),
    failures: ["Input force is high|Friction or poor ratio dominates|Operate unloaded with the scale|Align bearings and revise leverage", "The frame lifts or tips|Reaction forces exceed base support|Pull lightly while observing feet|Widen or clamp the base", "The load tilts|Lift point is off-center|Raise 2 cm and pause|Center the connection or add guides", "Force readings jump|Pull direction or speed changes|Film the scale orientation|Use a guide and steady pace"],
    tuning: "Reduce friction and frame flex before adding stages. Higher mechanical advantage lowers force but increases rope or handle travel and often adds more loss points.",
    extensions: ["Easier|Two-hundred-gram target|Compare direct and one pulley lift.", "Performance|Lowest-force score|Include a penalty for excessive input distance.", "Advanced|Efficiency audit|Calculate output work divided by input work for three designs."],
    related: ["pulley-elevator", "block-and-tackle-hoist", "water-hydraulic-lift"],
    builderMoment: "The load needed half the force and twice the rope. Conservation of work kept the receipt."
  },
  {
    number: 98,
    title: "Gear Ratio Race",
    slug: "gear-ratio-race",
    difficulty: "Intermediate",
    ageRange: "10-18",
    estimatedTime: "55-85 min",
    timeMinutes: 85,
    maxCost: 15,
    description: "Configure equal vehicles for speed or pulling force, predict their ratios, and compare performance in two fair races.",
    hook: "One ratio makes wheels spin faster; another trades speed for torque. The winning setup depends on whether the course rewards sprinting or pulling.",
    outcome: "Two vehicles complete a 2-metre speed run and a standard load-pull test with ratios recorded and no gear skipping.",
    concepts: ["Gear ratio", "Torque-speed tradeoff", "Fair testing"],
    input: "equal motor or hand-crank input rotation",
    output: "drive-wheel rotation and vehicle motion",
    motion: "rotary transmission-to-linear travel",
    losses: ["gear mesh friction", "wheel slip", "axle rubbing", "battery or crank variation"],
    principleName: "Torque-speed gearing",
    principle: "A large driver turning a small driven gear increases output speed but reduces ideal torque. A small driver turning a large gear reduces speed and increases ideal torque.",
    observe: "Mark one wheel and count rotations for ten input turns before placing either vehicle on the course.",
    materials: challengeMaterials("2|matching brick-compatible rover chassis|Provide fair vehicles", "2 sets|small and large gears with known tooth counts|Create ratios", "2|equal hand cranks or matched low-voltage motors|Provide input", "4|matching drive wheels|Contact the floor", "2 m|taped race lane|Measure speed", "1|standard 200 g pull sled|Measure pulling performance"),
    alternative: "Use one vehicle and test configurations sequentially when matching kits are unavailable.",
    hazard: "Use hand cranks or low-voltage motors only, keep gears covered where possible, and stop before stalled motors or batteries warm.",
    accessNote: "Use large color-and-tactile ratio labels and assign build, count, release, timing, and recording roles.",
    steps: ["Standardize the chassis|Match wheel diameter, axle spacing, mass, and alignment.|Roll both vehicles by hand.", "Choose two ratios|Build one speed-oriented and one torque-oriented pair.|Record driver and driven tooth counts.", "Brace the gear meshes|Support both sides of each axle and leave thin side clearance.|Turn ten input rotations by hand.", "Predict wheel speed|Calculate output rotations per input turn for both vehicles.|Mark predictions before racing.", "Set the speed course|Tape a straight 2-metre lane and use one release line.|Run three timed trials for each ratio.", "Build the pull test|Attach the same low-friction 200 g sled to each vehicle.|Use the same surface and line length.", "Run pulling trials|Measure distance moved in ten seconds or input turns.|Stop if teeth skip or motors stall.", "Compare tradeoffs|Graph speed-run time against pulling result.|Explain why no ratio wins every task."],
    math: math("Predict output speed", "output turns = input turns × driver teeth / driven teeth", ["Input = 10 turns", "Driver = 36 teeth", "Driven = 12 teeth"], "output = 10 × 36 / 12 = 30 turns", "The drive axle turns 30 ideal rotations for ten input rotations.", "Speed increases while ideal axle torque falls to one-third.", "Mesh friction and wheel slip change real travel."),
    test: test("Turn each drivetrain ten times while wheels are off the floor.", "Both vehicles finish three speed runs and move the standard sled without gear skipping.", "Time, wheel rotations, sled distance, and skipped teeth.", "gear ratio", "chassis, wheels, mass, input source, lane, sled, and release", ["1:3 speed ratio", "1:1 ratio", "3:1 torque ratio"]),
    failures: ["Gears skip under pull|Mesh supports spread|Hold the vehicle and load gently|Brace both axle bearings", "One car curves|Axles or wheels differ|Roll with drivetrain disconnected|Realign and match wheels", "Speed results vary|Release or input energy differs|Use a gate and count input turns|Standardize the start and source", "Torque setup stalls|Overall friction is high|Lift wheels and operate unloaded|Reduce bearing rub and sled drag"],
    tuning: "Align both vehicles before comparing ratios. Faster gearing magnifies friction and needs more input torque; torque gearing pulls more steadily but gives up wheel speed.",
    extensions: ["Easier|One-vehicle study|Compare two ratios sequentially.", "Performance|Mixed-course score|Combine sprint time and pull distance.", "Advanced|Power estimate|Use sled force and speed to estimate useful output power."],
    related: ["gear-ratio-demonstrator", "differential-steer-rover-chassis", "rubber-band-car"],
    builderMoment: "The speed car won the sprint and submitted no comment about the towing round."
  },
  {
    number: 99,
    title: "Friction Investigation Sled",
    slug: "friction-investigation-sled",
    difficulty: "Beginner",
    ageRange: "10-16",
    estimatedTime: "35-55 min",
    timeMinutes: 55,
    maxCost: 6,
    description: "Pull the same weighted sled across different surfaces and measure the force needed to start and sustain motion.",
    hook: "Friction is not one number for every surface. Starting friction and sliding friction can differ, and added normal force changes both.",
    outcome: "The team records repeatable starting and sliding force for at least three surfaces and explains one fair comparison.",
    concepts: ["Static friction", "Kinetic friction", "Normal force"],
    input: "horizontal pull measured by a spring scale",
    output: "sled motion across a test surface",
    motion: "linear force-to-linear sliding",
    losses: ["surface deformation", "pull-angle variation", "sled edge catching", "scale oscillation"],
    principleName: "Static and kinetic friction",
    principle: "Static friction resists the start of motion up to a maximum. Once sliding begins, kinetic friction often settles to a lower value for the same materials and load.",
    observe: "Watch the scale peak just before motion and compare it with the steadier reading while the sled moves.",
    materials: challengeMaterials("1|10 × 15 cm flat cardboard sled with raised edges|Carry the mass", "1|spring scale measuring 0-10 N|Measure pull force", "500 g|bagged washers in 100 g groups|Change normal force", "3|surface strips such as paper, felt, and plastic|Provide friction pairs", "1 m|taped pull lane|Standardize distance"),
    alternative: "Calibrate a rubber band against known masses if a spring scale is unavailable.",
    hazard: "Use bagged masses, pull away from faces, keep the lane at floor level, and stop if the spring scale is damaged.",
    accessNote: "Use a large pull handle, tactile surface labels, and separate pulling, reading, observing, and recording roles.",
    steps: ["Square the sled|Build a flat base with low walls and a centered pull loop.|Round the front edge so it cannot dig in.", "Mark the lane|Tape a straight 1-metre path and place the first surface strip flat.|Keep joints out of the measured section.", "Zero the scale|Hold it horizontal in the pull direction and check zero.|Use the same operator and height.", "Measure starting force|Increase pull slowly until the sled begins moving.|Record the highest reading before motion.", "Measure sliding force|Continue at steady slow speed and record the typical reading.|Repeat three times.", "Change the surface|Test two more materials with the same 300-gram load.|Reset the same start point.", "Change the load|On one surface, test 100, 300, and 500 grams.|Keep speed and pull angle fixed.", "Compare evidence|Average each set and separate start from sliding values.|Explain anomalies rather than deleting them."],
    math: math("Estimate friction coefficient", "coefficient μ = friction force / normal force", ["Sliding force = 1.5 N", "Normal force = 3.0 N"], "μ = 1.5 / 3.0 = 0.50", "The measured kinetic friction coefficient is about 0.50 for this pair.", "The value is experimental rather than a universal material constant.", "Pull angle and surface compression affect the estimate."),
    test: test("Pull the empty sled once and inspect whether its front edge catches.", "Three trials on each surface agree closely enough to compare starting and sliding force.", "Peak start force, steady sliding force, load, and surface.", "surface material", "sled, load, lane, pull angle, speed, operator, and scale", ["paper", "felt", "smooth plastic"]),
    failures: ["Readings jump wildly|Pull speed or angle changes|Film the scale and hand|Use a guide line and slower pull", "The sled tips|Pull loop is high or load off-center|Pull empty from the side view|Lower the loop and center mass", "One surface wrinkles|Strip is not secured|Inspect before each pull|Tape edges outside the lane", "Starting force is missed|Scale is read after motion begins|Have one observer call the peak|Use video or a force gauge hold function"],
    tuning: "Control the pull angle and speed before interpreting small differences. Added mass usually increases friction force, but the ratio may shift if soft surfaces deform.",
    extensions: ["Easier|Two-surface comparison|Use one load and three trials.", "Performance|Wheel conversion|Add wheels and compare rolling resistance.", "Advanced|Uncertainty|Report mean, range, and likely measurement error."],
    related: ["balloon-hovercraft", "tabletop-zipline-carrier", "gear-ratio-race"],
    builderMoment: "The sled preferred felt and provided a force reading to support its position."
  },
  {
    number: 100,
    title: "Center-of-Mass Balancing Sculpture",
    slug: "center-of-mass-balancing-sculpture",
    difficulty: "Beginner",
    ageRange: "10-17",
    estimatedTime: "40-65 min",
    timeMinutes: 65,
    maxCost: 6,
    description: "Arrange lightweight masses on a sculptural frame so the combined center of mass stays above a tiny support point.",
    hook: "A wide-looking sculpture can balance on one point when its masses place the combined center of mass below or directly above that support. Shape and mass distribution matter more than visual symmetry.",
    outcome: "The sculpture balances freely on a support no wider than 2 cm for at least 30 seconds and recovers from a gentle 2 cm sideways displacement.",
    concepts: ["Center of mass", "Torque", "Stable equilibrium"],
    input: "gravity acting on arranged masses",
    output: "restoring rotation toward the balance position",
    motion: "small angular disturbance-to-restoring swing",
    losses: ["support friction", "frame flex", "air movement", "mass shifting"],
    principleName: "Stable equilibrium",
    principle: "When the combined center of mass hangs below the support, a small tilt raises it. Gravity then creates a restoring torque that swings the sculpture back toward its lowest-energy position.",
    observe: "Shift one equal mass outward and watch how the resting angle changes before adding any new material.",
    materials: challengeMaterials("1|30 cm craft-stick or rolled-paper crossbar|Hold the sculpture arms", "2|30 cm strings|Suspend masses", "2|equal 50 g bagged washer sets|Lower the center of mass", "1|paper clip or shallow notch|Create the pivot", "1|rounded pencil eraser in a stable holder|Provide a small support", "6|light paper shapes|Create visual composition"),
    alternative: "Use clothespins as adjustable masses and a ruler as the crossbar.",
    hazard: "Use bagged lightweight masses, a stable low support, and keep faces away while testing a newly loaded frame.",
    accessNote: "Use large clips that slide without knots, high-contrast mass labels, and partner roles for holding and observing.",
    steps: ["Build the stable support|Fix a pencil vertically in a weighted cup with the eraser up.|Place it on a level table away from edges.", "Mark the crossbar|Find its midpoint and add equal distance marks on both sides.|Create a shallow central pivot notch.", "Attach low masses|Hang equal 50-gram bags from strings near both ends.|Keep each mass well below the pivot.", "Find the first balance|Set the notch on the eraser and slide one hanger until level.|Do not tape positions yet.", "Test restoring motion|Move one end sideways by 2 cm and release.|Watch whether it returns or falls away.", "Add the sculpture|Attach lightweight paper shapes without changing the heavy mass positions.|Rebalance by sliding hangers.", "Map mass changes|Move one mass outward 2 cm and predict the new angle.|Record the observed direction.", "Complete a 30-second test|Time balance and note oscillation decay.|Secure clips only after tuning."],
    math: math("Balance two moments", "left mass × left distance = right mass × right distance", ["Left = 50 g at 12 cm", "Right mass = 60 g"], "right distance = 50 × 12 / 60 = 10 cm", "A 60-gram right mass balances at about 10 cm.", "This balances turning moments around the pivot.", "The frame and decorations also contribute small moments."),
    test: test("Balance the bare crossbar and two equal masses before adding decoration.", "The sculpture balances 30 seconds and returns after a gentle 2 cm displacement.", "Resting angle, oscillation time, mass positions, and support slips.", "one mass position", "support, crossbar, other mass, room air, release, and timing", ["mass at 8 cm", "mass at 10 cm", "mass at 12 cm"]),
    failures: ["It tips immediately|Center of mass is above or far beside support|Remove decorations and test bare frame|Lower masses and recenter moments", "It slides off|Pivot notch is shallow or support tilted|Test with no hanging masses|Deepen slightly and level the base", "It never settles|Support friction is low and air is moving|Turn off fans and time longer|Add a tiny damping paper vane", "The crossbar bends|Masses are too heavy or far out|View from the side|Reduce mass or reinforce the bar"],
    tuning: "Lower masses improve stable recovery, while moving them outward increases their turning effect and structural demand. Keep decoration light so it remains a design variable rather than hidden ballast.",
    extensions: ["Easier|Symmetric mobile|Use equal masses at equal distances.", "Performance|Smallest support|Reduce contact width while maintaining 30-second balance.", "Advanced|Hidden asymmetry|Balance visibly unequal shapes and calculate counter-moments."],
    related: ["household-balance-scale", "paper-tower-challenge", "magnetic-maze"],
    builderMoment: "The sculpture looked impossible, balanced calmly, and declined further questions."
  }
] satisfies GuideBlueprint[];

export const classroomGuides = createGuides("Classroom challenges", blueprints);
